import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const canonical = JSON.parse(fs.readFileSync(path.join(import.meta.dirname, 'generated/cobria-canonical.json'), 'utf8'));
const { author, place, year, ecosystemVersion, coreVersion } = canonical.identity;
let tex = '';
if (!fs.existsSync(path.join(import.meta.dirname, 'index.html'))) {
  try { tex = fs.readFileSync(path.join(root, 'prelibro-catalogo-cobria.tex'), 'utf8'); }
  catch { tex = ''; }
}

function balanced(text, start) {
  let depth = 0;
  for (let i = start; i < text.length; i++) {
    if (text[i] === '{') depth++;
    if (text[i] === '}' && --depth === 0) return [text.slice(start + 1, i), i + 1];
  }
  throw new Error('Llave sin cierre');
}

const patterns = [];
let cursor = 0;
while ((cursor = tex.indexOf('\\Ficha{', cursor)) >= 0) {
  let at = cursor + '\\Ficha'.length;
  const fields = [];
  for (let i = 0; i < 9; i++) {
    while (/\s/.test(tex[at])) at++;
    const [value, next] = balanced(tex, at);
    fields.push(value); at = next;
  }
  patterns.push(fields); cursor = at;
}
if (patterns.length === 0) {
  const previous = fs.readFileSync(path.join(import.meta.dirname, 'index.html'), 'utf8');
  const strip = value => value.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
  for (const hit of previous.matchAll(/<article class="pattern[^>]*>([\s\S]*?)<\/article>/g)) {
    const block = hit[1];
    const title = strip((block.match(/<h1>([\s\S]*?)<\/h1>/)||[])[1]||'');
    const badges = [...block.matchAll(/<span class="badge">([\s\S]*?)<\/span>/g)].map(x=>strip(x[1]).replace(/^Evidencia:\s*/,''));
    const bodies = [...block.matchAll(/<section class="block[^>]*>[\s\S]*?<p>([\s\S]*?)<\/p><\/section>/g)].map(x=>strip(x[1]));
    if (title && badges.length === 2 && bodies.length === 6) patterns.push([title,...badges,...bodies]);
  }
}

const nuevasFichas = [
  ['Identidad documental estable','Adaptación COBRIA','Identidad y migración','Mantener una identidad independiente de ubicación, forma y proveedor.','Claves derivadas de rutas, nombres visibles o posiciones cambian durante una migración y rompen referencias.','Como el número de una muestra de campo: la etiqueta continúa aunque cambie de caja o estante.','Asigne una identidad opaca dentro del ámbito; trate claves externas como atributos versionados y valide colisiones en la frontera.','Úselo cuando un documento sobreviva importaciones, fusiones o cambios de colección. Evite codificar significado mutable en la identidad.','Mida colisiones, referencias huérfanas y tiempo de resolución. Se relaciona con Objeto canónico, Revisión obsoleta rechazada y Catálogo versionado.'],
  ['Validación en frontera','Patrón establecido','Contrato verificable','Impedir que formas inválidas entren al núcleo documental.','Aceptar primero y corregir después dispersa supuestos y convierte cada lector en un validador distinto.','Como una estación biológica: cada muestra se registra y revisa antes de entrar al archivo.','La frontera comprueba forma, ámbito, revisión, vocabulario y reglas invariantes; devuelve errores estructurados sin escritura parcial.','Aplíquelo en API, importadores, consumidores y herramientas. Conserve el dato crudo separado cuando sea evidencia legítima.','Mida rechazos por causa, campos desconocidos y escrituras parciales. Se conecta con Contrato versionado y Herramienta de agente gobernada.'],
  ['Contrato documental versionado','Adaptación COBRIA','Compatibilidad demostrada','Evolucionar documentos sin exigir una migración instantánea de todo el conjunto.','Cambiar el significado de un campo bajo el mismo nombre produce lectores temporalmente incompatibles.','Como una guía de especies por ediciones: cada observación indica con qué edición fue clasificada.','Cada documento declara versión; lectores admiten un intervalo explícito y las transformaciones entre versiones son deterministas e idempotentes.','Úselo ante cambios aditivos o incompatibles. Mantenga pruebas de lectura hacia atrás y hacia delante durante la convivencia.','Mida documentos por versión, fallos de conversión y consumidores antiguos. Se relaciona con Catálogo versionado y Publicación por versión.'],
  ['Lectura coherente por revisión','Contrato compuesto','Consistencia observable','Evitar respuestas formadas por fragmentos de revisiones incompatibles.','Consultar varias proyecciones puede mezclar estados aunque cada lectura aislada sea correcta.','Como comparar fotografías de una misma parcela: todas deben pertenecer al mismo levantamiento.','Propague revisión objetivo o corte; acepte solo fragmentos compatibles y declare degradación cuando no pueda completarse.','Aplíquelo en vistas compuestas, informes y recuperación aumentada. No prometa coherencia que el motor o las proyecciones no sostienen.','Mida mezclas detectadas, abstenciones y atraso por revisión. Se vincula con Reconstrucción incremental y Recuperación limitada por ámbito.'],
  ['Ventana de frescura declarada','Adaptación COBRIA','Acuerdo medible','Hacer explícito cuánto atraso puede tolerar cada lectura.','Sin un límite declarado, una proyección aparentemente rápida puede entregar información inaceptablemente antigua.','Como un boletín meteorológico: su utilidad depende de cuándo fue observado y cuándo se consulta.','Cada proyección publica última revisión aplicada, tiempo de actualización y límite contratado; el lector decide esperar, degradar o fallar.','Úselo en derivados asíncronos. Defina ventanas por decisión, no una cifra universal para todo el sistema.','Mida edad, percentiles de atraso e incumplimientos. Se conecta con Reconstrucción incremental y Frontera lectura-escritura.'],
  ['Manifiesto de proyección','Adaptación COBRIA','Procedencia completa','Explicar exactamente con qué fuentes y transformación se produjo un derivado.','Una copia puede parecer correcta y aun mezclar semillas, versiones o cortes distintos.','Como la ficha de una colección científica: origen, fecha, método y responsable acompañan al conjunto.','Guarde fuentes, cortes, versiones, parámetros, semilla, huellas y resultado de verificación como manifiesto inmutable.','Úselo en índices, conjuntos analíticos y publicaciones. El manifiesto referencia secretos sin copiarlos.','Mida manifiestos incompletos, huellas inválidas y tiempo de reproducción. Se relaciona con Conjunto reproducible y Reparación verificable.'],
  ['Partición analítica sin fuga','Contrato compuesto','Evaluación válida','Separar entrenamiento, validación y prueba sin contaminar tiempo, entidad ni ámbito.','Una partición aleatoria puede colocar revisiones de la misma entidad a ambos lados y exagerar la calidad del modelo.','Como estudiar aves por rutas distintas: no se cuenta la misma bandada como descubrimiento independiente.','Particione primero por entidad y tiempo, luego por ámbito; congele reglas y audite intersecciones antes de calcular métricas.','Úselo en minería de datos y aprendizaje automático. Documente exclusiones y conserve una prueba negativa de contaminación.','Mida intersecciones, deriva temporal y rendimiento por ámbito. Se conecta con Conjunto reproducible y Característica versionada.'],
  ['Abstención con evidencia','Control de IA','Seguridad y honestidad','Responder solo cuando la evidencia autorizada sostiene la salida.','Un sistema generativo puede completar vacíos con lenguaje plausible o citar fragmentos inexistentes.','Como una guía responsable: si no observa señales suficientes, declara que no puede identificar la especie.','Defina umbrales, cobertura mínima, citas válidas y causas de abstención; la generación recibe únicamente evidencia autorizada.','Úselo en asistentes y automatizaciones. La abstención debe ser útil: explique qué falta sin revelar material prohibido.','Mida precisión, cobertura, citas válidas, fugas y abstención apropiada. Se relaciona con Recuperación limitada por ámbito.'],
  ['Presupuesto de derivados','Adaptación COBRIA','Costo gobernado','Limitar cuántas copias optimizadas puede sostener responsablemente un sistema.','Cada proyección mejora una lectura local, pero añade escritura, almacenamiento, monitoreo y carga cognitiva.','Como senderos en una reserva: cada nuevo recorrido necesita propósito, mantenimiento y cierre seguro.','Toda propuesta declara beneficio, costo total, propietario, fecha de revisión y criterio de retiro antes de ser publicada.','Úselo al diseñar o revisar proyecciones. Agrupe necesidades compatibles antes de crear otra copia.','Mida uso, costo por consulta, atraso e incidentes. Se conecta con Frontera lectura-escritura y Retiro de proyección.'],
  ['Auditoría narrativa reconstruible','Experimental','Explicación reproducible','Convertir eventos técnicos en una historia verificable de decisión y cambio.','Los registros aislados muestran acciones, pero no siempre explican quién autorizó, qué versión se usó y qué consecuencia ocurrió.','Como un cuaderno de campo: cada observación enlaza lugar, momento, responsable y evidencia.','Componga una vista temporal desde eventos inmutables; mantenga enlaces al documento, revisión, ámbito, política y resultado, sin volverla autoridad.','Úselo en incidentes, decisiones asistidas y revisión regulatoria. Proteja datos sensibles y aplique retención diferenciada.','Mida eventos sin enlace, secuencias imposibles y tiempo de explicación. Se conecta con Dato fechado, Cola de salida y Herramienta gobernada.']
];
if (patterns.length === 20) patterns.push(...nuevasFichas);

function clean(value) {
  return value
    .replace(/``([^']+)''/g, '“$1”')
    .replace(/\\Delta/g, 'Δ').replace(/\\ll/g, '≪').replace(/\\leq/g, '≤')
    .replace(/\\,/g, ' ').replace(/~|\\par/g, ' ')
    .replace(/\\text(?:bf|sf)\{([^{}]+)\}/g, '$1')
    .replace(/\$([^$]+)\$/g, '<em>$1</em>')
    .replace(/--/g, '—').replace(/\\/g, '')
    .replace(/\s+/g, ' ').trim();
}

const visualByPattern = {
  2: ['assets/familia-modelado-validacion-v1.png', 'Antes: los ámbitos se mezclan. Después: el acceso decide el sendero antes de recuperar documentos.'],
  3: ['assets/catalogo-versionado-v1.png', 'Las ediciones separadas permiten interpretar cada valor y aislar los desconocidos.'],
  6: ['assets/ecosistema-cobria-panoramico-v4.png', 'La fuente permanece intacta mientras una versión derivada se reconstruye y verifica.'],
  15: ['assets/familia-analitica-ia-v1.png', 'La evidencia conserva un hilo visible desde el documento hasta la recuperación autorizada.']
};

const exercises = [
  'Dibuje las rutas de escritura actuales. Marque cuál puede cambiar una regla de dominio y cierre las demás.',
  'Elija un hecho tardío y reconstruya qué se sabía antes y después de su registro.',
  'Escriba tres pruebas negativas: ámbito ausente, manipulado y válido con recurso ajeno.',
  'Tome un código ambiguo y defina versión, vigencia, sustitución y cuarentena.',
  'Seleccione una consulta lenta y escriba exactamente filtros, orden, salida y frescura.',
  'Quite todos los campos no usados por la consulta y vuelva a medir bytes y costo.',
  'Elimine una copia en un entorno aislado y regenérela sin tocar la fuente.',
  'Procese dos veces el mismo lote y compare el resultado con una reconstrucción total.',
  'Construya una candidata, interrumpa antes del cambio y compruebe que la activa sigue completa.',
  'Entregue dos veces el mismo mensaje y compruebe que solo existe un efecto.',
  'Envíe una revisión antigua y verifique rechazo, auditoría y ausencia de regresión.',
  'Interrumpa el publicador después de guardar la entidad y confirme que el evento sigue recuperable.',
  'Corrompa una muestra derivada, detecte la divergencia y repare desde canónicos.',
  'Reconstruya el mismo corte dos veces y compare manifiesto, conteos y huellas.',
  'Cambie una definición de variable y confirme que produce una versión nueva.',
  'Intente recuperar un fragmento de otro ámbito y compruebe que nunca fue candidato.',
  'Repita una acción de alto riesgo sin confirmación y exija abstención auditable.',
  'Calcule el punto de equilibrio con costos medidos y repita con el doble de escrituras.',
  'Añada primero un índice documental equivalente y mida antes de crear una copia.',
  'Identifique una proyección sin uso, simule el retiro y verifique consumidores y reversión.'
  ,'Cambie ubicación y nombre externo de diez documentos y demuestre que sus referencias internas permanecen válidas.'
  ,'Diseñe cinco entradas inválidas y compruebe rechazo completo, causa legible y ausencia de efectos parciales.'
  ,'Lea documentos de tres versiones, migre dos veces la misma muestra y compare huellas.'
  ,'Combine dos proyecciones con atraso distinto y compruebe que nunca se presenta una revisión mezclada.'
  ,'Supere deliberadamente la ventana de frescura y verifique espera, degradación y fallo según contrato.'
  ,'Reconstruya una proyección únicamente desde su manifiesto y registre cualquier dato implícito faltante.'
  ,'Particione un conjunto por entidad y tiempo; escriba una prueba que falle ante cualquier intersección.'
  ,'Retire evidencia suficiente y compruebe que la respuesta se abstiene con una explicación segura.'
  ,'Calcule el costo anual de tres derivados y retire o combine el que no justifique su mantenimiento.'
  ,'Reconstruya la narración de un incidente desde eventos y señale cada afirmación sin evidencia enlazada.'
];

const contracts = [
  'guardar(cambio) → validar → escribirCanónico → emitirRevisión',
  'registrar(hecho, válidoEn, conocidoEn, procedencia)',
  'obtener(ámbito, identidad) o fallarAntesDeLeer()',
  'resolver(clave, versión, fecha) o ponerEnCuarentena()',
  'proyectar(fuente, transformación, versión, ámbito)',
  'cubrir(filtros, orden, salida) sinCamposExtra()',
  'candidata = reconstruir(canónicos); verificar(candidata); publicar()',
  'desde(puntoDeControl).procesarUnaVezPorRevisión()',
  'construir(vNueva); verificar(); cambiarAlias(); conservar(vAnterior)',
  'si procesado(idMensaje) entonces noHacerNada()',
  'si revisiónEsperada ≠ revisiónActual entonces rechazar()',
  'enUnaOperación { guardarCanónico(); guardarEventoSalida(); }',
  'si !equivalente(derivado, esperado) entonces reconstruirYVerificar()',
  'conjunto = construir(corte, fuentes, versiones, semilla)',
  'característica = calcular(definición, tiempoEvento, versión)',
  'candidatos = buscar(dentroDe(ámbito, política), consulta)',
  'herramienta.validar(); exigirCapacidad(); confirmarSiRiesgo(); auditar()',
  'adoptar si ahorroLectura > costoEscritura + costoOperacional',
  'medir(consultaConÍndice) antesDe crearProyección()',
  'detenerConsumidores(); retirarProductor(); esperar(); eliminarDerivado()'
  ,'identidad = asignar(ámbito); referencias.usar(identidad)'
  ,'validar(entrada, contrato, ámbito) o rechazarSinEfectos()'
  ,'leer(según versión); migrar(de, hacia) deFormaIdempotente()'
  ,'leerTodoEn(revisiónObjetivo) o declararDegradación()'
  ,'si edad > ventana entonces esperar | degradar | fallar'
  ,'manifiesto = sellar(fuentes, cortes, versiones, semilla, huellas)'
  ,'partirPor(entidad, tiempo, ámbito); exigir(intersección = ∅)'
  ,'si evidenciaInsuficiente entonces abstener(causaSegura)'
  ,'autorizarDerivado soloSi beneficio > costoTotal y tieneRetiro'
  ,'narrar(eventosOrdenados); exigirEnlace(documento, revisión, política)'
];

const names = ['Propósito','Problema','Analogía','Solución y contrato','Aplicación responsable','Métricas, costos y relaciones'];
const familyByPattern = [
  'Modelado documental','Modelado documental','Seguridad por ámbito','Catálogos y vocabularios',
  'Proyecciones de lectura','Proyecciones de lectura','Reconstrucción','Reconstrucción','Eventos y consistencia','Eventos y consistencia',
  'Eventos y consistencia','Eventos y consistencia','Reconstrucción','Analítica reproducible','Analítica reproducible',
  'IA con procedencia','IA con procedencia','Gobernanza del ciclo de vida','Gobernanza del ciclo de vida','Gobernanza del ciclo de vida',
  'Modelado documental','Modelado documental','Modelado documental','Eventos y consistencia','Eventos y consistencia',
  'Reconstrucción','Analítica reproducible','IA con procedencia','Gobernanza del ciclo de vida','Modelado documental'
];
const visualByFamily = {
  'Modelado documental': ['assets/familia-modelado-validacion-v1.png','La identidad, la validación y las versiones convierten entradas dispersas en documentos interpretables.'],
  'Tiempo y evidencia': ['assets/familia-eventos-consistencia-v1.png','El orden, el atraso y la procedencia viajan con cada observación.'],
  'Seguridad por ámbito': ['assets/repositorio-ambito-sin-felinos-v2.png','El sendero autorizado se decide antes de recuperar documentos.'],
  'Catálogos y vocabularios': ['assets/catalogo-versionado-v1.png','Cada edición conserva el significado con el que fue interpretado un valor.'],
  'Proyecciones de lectura': ['assets/ecosistema-cobria-panoramico-v4.png','Los nidos sirven lecturas distintas sin desplazar la autoridad de las raíces.'],
  'Reconstrucción': ['assets/ecosistema-cobria-panoramico-v4.png','Una representación derivada vuelve a producirse y se compara con la fuente.'],
  'Publicación y migración': ['assets/ecosistema-cobria-panoramico-v4.png','La versión candidata se verifica antes de sustituir a la activa.'],
  'Eventos y consistencia': ['assets/familia-eventos-consistencia-v1.png','Eventos repetidos, tardíos y ordenados atraviesan una ruta observable.'],
  'Analítica reproducible': ['assets/familia-analitica-ia-v1.png','Particiones, transformaciones y resultados mantienen un linaje visible.'],
  'IA con procedencia': ['assets/linaje-ia-v1.png','La respuesta enlaza evidencia autorizada o se abstiene cuando no la posee.'],
  'Decisión arquitectónica': ['assets/familia-gobernanza-retiro-v1.png','Cada sendero optimizado exige propósito, medición, mantenimiento y posible cierre.'],
  'Gobernanza del ciclo de vida': ['assets/familia-gobernanza-retiro-v1.png','La arquitectura conserva rutas útiles y retira las que ya no justifican su costo.']
};
const participants = ['Fuente canónica','Contrato','Repositorio','Catálogo','Proyector','Verificador','Consumidor'];
const related = (index) => [patterns[(index + 1) % patterns.length][0], patterns[(index + 6) % patterns.length][0], patterns[(index + 13) % patterns.length][0]];
const practicalExamples = JSON.parse(fs.readFileSync(path.join(import.meta.dirname,'practical-examples.json'),'utf8'));
const codeEscape = value => value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const implementations = (p, index) => {
  if (practicalExamples[index]?.code) return practicalExamples[index].code;
  const name = clean(p[0]).replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ0-9]/g, '') || `Patron${index + 1}`;
  const contract = clean(p[3]);
  return {
    TypeScript: `type Documento = { id: string; ambito: string; revision: number };\n\nclass ${name} {\n  ejecutar(doc: Documento): Documento {\n    if (!doc.ambito) throw new Error('Ámbito requerido');\n    // ${contract}\n    return { ...doc };\n  }\n}`,
    Python: `from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Documento:\n    id: str\n    ambito: str\n    revision: int\n\ndef aplicar(doc: Documento):\n    assert doc.ambito, "Ámbito requerido"\n    # ${contract}\n    return doc`,
    Java: `record Documento(String id, String ambito, long revision) {}\n\nfinal class ${name} {\n  Documento ejecutar(Documento doc) {\n    if (doc.ambito().isBlank())\n      throw new IllegalArgumentException("Ámbito requerido");\n    // ${contract}\n    return doc;\n  }\n}`,
    Go: `type Documento struct {\n  ID string\n  Ambito string\n  Revision int64\n}\n\nfunc Aplicar(doc Documento) (Documento, error) {\n  if doc.Ambito == "" {\n    return doc, errors.New("ámbito requerido")\n  }\n  // ${contract}\n  return doc, nil\n}`
  };
};
const cards = patterns.map((p, index) => {
  const body = p.slice(3).map(clean);
  const blocks = body.map((value, i) => `<section class="block ${i === 2 ? 'analogy' : ''} ${i === 3 ? 'solution' : ''}"><h2>${names[i]}</h2><p>${value}</p></section>`).join('');
  const family = familyByPattern[index];
  const visual = visualByPattern[index] || visualByFamily[family];
  const illustration = visual ? `<figure class="story-illustration"><img src="${visual[0]}" alt="Ilustración pedagógica de ${clean(p[0])}"><figcaption>${visual[1]}</figcaption></figure>` : '';
  const links = related(index);
  const mechanism = `<article class="book-page mechanism-page"><div class="eyebrow">Mecánica · ${family}</div><h1>Cómo funciona ${clean(p[0])}</h1><p class="lead">La estructura convierte el propósito en responsabilidades separadas y comprobables.</p><div class="flow">${participants.slice(0,5).map((x,i)=>`<div><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><h2>Secuencia</h2><ol class="steps"><li>El consumidor expresa identidad, ámbito, revisión y necesidad de lectura.</li><li>El contrato valida precondiciones antes de tocar la colección.</li><li>El repositorio recupera o modifica únicamente el documento autorizado.</li><li>El mecanismo produce evidencia versionada y nunca suplanta la autoridad.</li><li>El verificador compara resultado, límites y caso negativo.</li></ol><h2>Pseudocódigo neutral</h2><pre>${contracts[index]}</pre><div class="note"><strong>Invariante principal.</strong> ${body[0]}</div><footer>COBRIA · Mecánica del patrón ${String(index+1).padStart(2,'0')}</footer></article>`;
  const decision = `<article class="book-page decision-page"><div class="eyebrow">Decidir con criterio</div><h1>Cuándo usarlo y cuándo evitarlo</h1><div class="decision-grid"><section><h2>Conviene cuando</h2><ul><li>la tensión descrita aparece en mediciones o incidentes;</li><li>existe una persona responsable del contrato;</li><li>puede probarse reconstrucción, rechazo o abstención;</li><li>el beneficio supera el costo operativo completo.</li></ul></section><section class="avoid"><h2>No conviene cuando</h2><ul><li>un índice o validación más simple resuelve la necesidad;</li><li>la copia no tiene consumidor ni límite de frescura;</li><li>se intenta ocultar una autoridad ambigua;</li><li>no existe mecanismo de reversión o retiro.</li></ul></section></div><h2>Consecuencias</h2><table><tr><th>Beneficio</th><th>Costo o riesgo</th><th>Control</th></tr><tr><td>${body[0]}</td><td>${body[1]}</td><td>Contrato, métrica y prueba negativa</td></tr><tr><td>Responsabilidad visible</td><td>Más disciplina documental</td><td>Rúbrica y revisión periódica</td></tr></table><h2>Errores frecuentes</h2><p>Aplicarlo por nombre, omitir el ámbito, aceptar revisiones implícitas o medir únicamente el caso feliz. La solución se considera incompleta si no puede explicar su fallo.</p><div class="connections"><strong>Conecta con:</strong> ${links.join(' · ')}</div><footer>COBRIA · Decisión arquitectónica</footer></article>`;
  const lab = `<article class="lab-page">
    <div class="eyebrow">Laboratorio de campo · ${String(index + 1).padStart(2,'0')}</div>
    <h1>${clean(p[0])}</h1>
    <p class="lab-lead">Ahora convierta la idea en una prueba pequeña, observable y reversible.</p>
    <section class="field-card"><h2>Situación para diagnosticar</h2><p>${body[1]}</p></section>
    <div class="lab-grid"><section><h2>Ejercicio</h2><p>${exercises[index]}</p></section><section><h2>Resultado que debe conservar</h2><p>${body[0]}</p></section></div>
    <section><h2>Contrato mínimo</h2><pre>${contracts[index]}</pre></section>
    <div class="lab-grid"><section><h2>Preguntas de revisión</h2><ul><li>¿Quién posee la autoridad?</li><li>¿Dónde aparece el ámbito y la versión?</li><li>¿Cómo se prueba el fallo?</li><li>¿Cómo se revierte o reconstruye?</li></ul></section><section><h2>Evidencia para guardar</h2><ul><li>manifiesto y versión;</li><li>entrada y resultado esperado;</li><li>métrica y límite;</li><li>captura del caso negativo.</li></ul></section></div>
    <section class="field-card relation"><h2>Conexiones</h2><p>${body[5]}</p></section>
    <footer>COBRIA · Laboratorio NoSQL · Billy Jak Cordero Porras</footer>
  </article>`;
  const reference = `<article class="book-page reference-page"><div class="eyebrow">Tarjeta de referencia · ${String(index+1).padStart(2,'0')}</div><h1>${clean(p[0])}</h1><div class="reference-grid"><section><h2>Contrato de aceptación</h2><ol><li>Preparar un documento válido y otro inválido.</li><li>Ejecutar ${clean(p[0]).toLowerCase()} bajo un ámbito conocido.</li><li>Comprobar resultado, revisión y procedencia.</li><li>Repetir, interrumpir o reconstruir según corresponda.</li><li>Guardar manifiesto, métricas y causa de cualquier exclusión.</li></ol></section><section><h2>Lista de comprobación</h2><ul class="checklist"><li>Autoridad identificada</li><li>Ámbito obligatorio</li><li>Contrato versionado</li><li>Caso negativo probado</li><li>Observabilidad suficiente</li><li>Reversión o reconstrucción</li></ul></section></div><h2>Señales que debe observar</h2><p>${body[5]}</p><h2>Preguntas para revisión de diseño</h2><div class="question-grid"><p>¿Qué afirmación concreta vuelve verdadera este patrón?</p><p>¿Qué dato demuestra que continúa funcionando?</p><p>¿Qué ocurre si se repite, atrasa o interrumpe?</p><p>¿Cómo se retira sin perder la fuente?</p></div><div class="note"><strong>Regla de salida.</strong> Si no puede responder las cuatro preguntas con evidencia, el patrón aún no está implementado.</div><footer>COBRIA · Referencia rápida</footer></article>`;
  const code = implementations(p, index);
  const practical = practicalExamples[index];
  const codePage = `<article class="book-page code-page"><div class="eyebrow">Implementación comparada · ${String(index+1).padStart(2,'0')}</div><h1>${clean(p[0])}</h1><div class="book-story"><strong>${practical.escena}</strong><p>${practical.problema}</p><small>Resultado: ${practical.resultado}</small></div><p class="code-lead">El mismo caso se expresa en cuatro lenguajes. Identifique participantes y contrato antes de adaptar el ejemplo a su almacén documental.</p><div class="code-grid">${Object.entries(code).map(([language,value])=>`<section><h2>${language}</h2><pre>${codeEscape(value)}</pre></section>`).join('')}</div><div class="note"><strong>Prueba mínima.</strong> Ejecute el caso válido, elimine el dato que delimita la operación y compruebe que el fallo conserva evidencia.</div><footer>COBRIA · Código multilenguaje · Billy Jak Cordero Porras</footer></article>`;
  return `<article class="pattern ${visual ? 'illustrated' : ''}">
    <header class="pattern-head"><div class="pattern-number">${String(index + 1).padStart(2,'0')}</div><h1>${clean(p[0])}</h1></header>
    <div class="badges"><span class="badge">${clean(p[1])}</span><span class="badge">Evidencia: ${clean(p[2])}</span></div>
    <div class="pattern-grid">${illustration}${blocks}</div>
    <footer>COBRIA · Arquitecturas NoSQL reconstruibles · Billy Jak Cordero Porras</footer>
  </article>${mechanism}${decision}${lab}${reference}${codePage}`;
}).join('\n');

const frontMatter = `<section class="book-page title-page"><div class="eyebrow">Edición ecosistema ${ecosystemVersion}</div><h1>COBRIA</h1><p class="lead">Manual de diseño, capas, datos y software verificable</p><div class="title-rule"></div><p>${author}<br>${place} · ${year}</p><div class="note">Libro, guía y laboratorio para aprender desde los fundamentos hasta patrones NoSQL reconstruibles, calidad, operación, analítica e inteligencia artificial.</div></section>
<section class="book-page bibliographic-page"><div class="eyebrow">Información de la obra digital</div><h1>Datos de esta edición</h1><dl class="bibliographic-grid"><dt>Título</dt><dd>COBRIA: Diseño, capas, datos y software verificable</dd><dt>Subtítulo</dt><dd>Catálogo pedagógico de patrones NoSQL reconstruibles</dd><dt>Autor</dt><dd>${author}</dd><dt>Versión</dt><dd>Edición ecosistema ${ecosystemVersion}</dd><dt>Lugar y fecha</dt><dd>${place}, ${year}</dd><dt>Idioma</dt><dd>Español</dd><dt>Formato</dt><dd>Documento pedagógico digital en PDF</dd><dt>Distribución</dt><dd>Publicación independiente y gratuita del autor</dd></dl><div class="rights-box"><strong>Uso y alcance.</strong> Material educativo de acceso libre para estudio, docencia, investigación y adaptación con atribución. No constituye una edición comercial ni un estándar certificado. COBRIA integra y formaliza principios existentes con contratos y mecanismos propios; no afirma que cada elemento sea una invención aislada. Los ejemplos requieren validación antes de emplearse en producción.</div></section>
<section class="book-page bibliographic-page"><div class="eyebrow">Sinopsis</div><h1>Una arquitectura que conserva el camino de regreso</h1><div class="synopsis-box"><p>COBRIA es una propuesta pedagógica para diseñar sistemas NoSQL documentales cuya información pueda explicarse, comprobarse y reconstruirse. Organiza treinta patrones alrededor de fuentes canónicas, límites de acceso, catálogos versionados, proyecciones de lectura, eventos idempotentes, analítica reproducible e inteligencia artificial con procedencia.</p><p>El libro combina analogías inspiradas en la naturaleza de Costa Rica, contratos verificables, decisiones arquitectónicas, laboratorios y ejemplos en TypeScript, Python, Java y Go. Está dirigido a estudiantes, docentes, personas desarrolladoras, arquitectos de software y equipos que necesitan optimizar lecturas sin perder autoridad, trazabilidad ni capacidad de auditoría.</p></div><h2>Palabras clave</h2><p>Arquitectura de software; NoSQL; bases de datos documentales; patrones de diseño; trazabilidad; reconstrucción; minería de datos; inteligencia artificial; gobernanza de datos.</p><h2>Clasificación temática sugerida</h2><p>Computación y tecnología · Ingeniería de software · Bases de datos · Arquitectura de sistemas.</p></section>
<section class="book-page bibliographic-page"><div class="eyebrow">Sobre el autor</div><h1>Billy Jak Cordero Porras</h1><div class="author-profile"><div class="author-monogram">BJ</div><div><p>Billy Jak Cordero Porras es un joven cotobruseño aficionado a la informática y al desarrollo de software. Desde temprana edad ha construido sistemas para aprender y atender problemas cotidianos. Su curiosidad lo llevó a estudiar de forma autodidacta arquitectura de software, bases de datos, gestión de información e inteligencia artificial.</p><p>El trabajo con proyectos diversos lo enfrentó repetidamente al problema de conservar información comprensible, segura, trazable y útil. A partir de experimentación, comparación de patrones y revisión de errores formalizó COBRIA como investigación, artículo, libro y recurso pedagógico interactivo de acceso abierto.</p></div></div><div class="note"><strong>Principio del autor.</strong> La investigación universitaria y la creación de soluciones deben producir conocimiento comprensible, verificable y de interés público.</div></section>
<section class="book-page"><div class="eyebrow">Nota del autor</div><h1>Un lenguaje para conversar sobre datos</h1><p class="lead">COBRIA nació de observar una estructura repetida en sistemas reales: objetos que conservan reglas, repositorios que delimitan acceso, servicios que coordinan decisiones, catálogos que estabilizan significado y derivados que aceleran consultas o alimentan analítica.</p><p>Este libro no presenta cada mecanismo como una invención aislada. Reúne ideas conocidas, adaptaciones y contratos compuestos dentro de una propuesta evaluable. El lector puede adoptar una parte, medirla y rechazarla si no produce beneficio.</p><h2>Antecedentes conceptuales</h2><p>La propuesta dialoga con la tradición de patrones de diseño (Gamma et al., 1994), patrones de arquitectura empresarial (Fowler, 2002), diseño dirigido por el dominio (Evans, 2003), persistencia políglota NoSQL (Sadalage &amp; Fowler, 2012) y sistemas intensivos en datos (Kleppmann, 2017). La organización de citas y referencias sigue los criterios generales de APA 7 (American Psychological Association, 2020).</p><h2>Promesa pedagógica</h2><p>Cada capítulo responde cinco preguntas: qué tensión existe, cómo se reconoce, qué responsabilidades introduce la solución, qué puede salir mal y qué evidencia demuestra su funcionamiento.</p><div class="note"><strong>Alcance.</strong> Todo el contenido se formula para almacenes NoSQL documentales, sin depender de un producto particular.</div></section>
<section class="book-page"><div class="eyebrow">Fundamentos</div><h1>Objeto, dato, servicio y catálogo</h1><div class="concept-grid"><article><h2>Objeto</h2><p>Representa identidad y reglas que deben conservarse juntas.</p></article><article><h2>Dato fechado</h2><p>Registra valor, tiempo válido, tiempo conocido y procedencia.</p></article><article><h2>Repositorio</h2><p>Expresa el límite de acceso y evita consultas sin ámbito.</p></article><article><h2>Servicio</h2><p>Coordina una decisión que atraviesa varios objetos o mecanismos.</p></article><article><h2>Catálogo</h2><p>Estabiliza el significado de códigos, unidades y versiones.</p></article><article><h2>Proyección</h2><p>Optimiza una lectura y puede reconstruirse desde la autoridad.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Fundamentos</div><h1>Patrón, contrato, mecanismo y decisión</h1><table><tr><th>Concepto</th><th>Pregunta</th><th>Evidencia</th></tr><tr><td>Patrón</td><td>¿Qué tensión recurrente resuelve?</td><td>Contexto, solución y consecuencias</td></tr><tr><td>Contrato</td><td>¿Qué debe cumplirse siempre?</td><td>Precondición, resultado y fallo</td></tr><tr><td>Mecanismo</td><td>¿Cómo se ejecuta?</td><td>Participantes y secuencia</td></tr><tr><td>Decisión</td><td>¿Por qué conviene aquí?</td><td>Alternativas, costo y métrica</td></tr></table><p class="lead">COBRIA exige las cuatro capas. Un nombre sin contrato inspira; no gobierna. Un mecanismo sin decisión funciona; quizá no conviene.</p></section>
<section class="book-page"><div class="eyebrow">Especificación congelada</div><h1>COBRIA Core ${coreVersion}</h1><p class="lead">El núcleo normativo convierte el catálogo en una arquitectura comprobable.</p><table><tr><th>Nivel</th><th>Obligaciones</th></tr><tr><td>C1 · Fundamental</td><td>Autoridad, ámbito, identidad, revisión y frontera de escritura.</td></tr><tr><td>C2 · Reconstruible</td><td>C1 más transformación versionada, equivalencia, idempotencia, reconstrucción y publicación segura.</td></tr><tr><td>C3 · Gobernado</td><td>C2 más procedencia, frescura, observabilidad, responsable y retiro.</td></tr></table><div class="note"><strong>Regla de conformidad.</strong> Una implementación solo declara un nivel cuando supera todas sus pruebas obligatorias. El alcance confirmatorio se limita a sistemas NoSQL documentales.</div></section>
<section class="book-page"><div class="eyebrow">Precisión conceptual · Core 1.1</div><h1>Qué es COBRIA y qué no es</h1><p class="lead">Una propuesta arquitectónica verificable, no una estructura de datos ni un producto de almacenamiento.</p><div class="concept-grid"><article><h2>Núcleo</h2><p>Invariantes y requisitos obligatorios.</p></article><article><h2>Patrones</h2><p>Soluciones recurrentes que ayudan a cumplirlos.</p></article><article><h2>Mecanismos</h2><p>Índices, proyecciones, manifiestos y revisiones.</p></article><article><h2>Método</h2><p>Inventariar, decidir, verificar, observar y retirar.</p></article><article><h2>Adaptadores</h2><p>Implementaciones intercambiables para motores NoSQL.</p></article><article><h2>Evidencia</h2><p>Pruebas, métricas, límites y resultados reproducibles.</p></article></div><div class="note"><strong>Afirmación responsable.</strong> La contribución es la composición formalizada y comprobable de mecanismos conocidos; no la invención aislada de cada pieza.</div></section>
<section class="book-page"><div class="eyebrow">Caso completo · Core 1.2</div><h1>Cuando desaparece el índice del bosque</h1><p class="lead">Un solo recorrido conecta documento, contrato, fallo, reconstrucción, analítica e IA.</p><ol class="steps"><li>Una observación canónica declara identidad, ámbito, revisión y versión.</li><li>Un contrato produce una proyección de búsqueda sin autoridad propia.</li><li>La proyección activa se elimina de forma controlada.</li><li>Una candidata se reconstruye desde documentos y catálogo congelados.</li><li>La equivalencia se comprueba antes de cambiar el alias.</li><li>El corte analítico conserva partición temporal y manifiesto.</li><li>La recuperación para IA filtra ámbito antes de similitud y se abstiene sin evidencia.</li></ol><div class="note"><strong>Resultado.</strong> La búsqueda vuelve sin inventar datos; una revisión antigua no reemplaza la nueva y otro ámbito obtiene cero documentos.</div></section>
<section class="book-page"><div class="eyebrow">Aprender por contraste</div><h1>Ocho diseños que parecen funcionar</h1><div class="concept-grid"><article><h2>Proyección editable</h2><p>Crea dos autoridades.</p></article><article><h2>Ámbito al final</h2><p>Filtra después de revelar candidatos.</p></article><article><h2>Revisión obsoleta</h2><p>Hace retroceder el estado visible.</p></article><article><h2>Vector sin manifiesto</h2><p>Oculta corpus, modelo y corte.</p></article><article><h2>Fuga temporal</h2><p>El futuro contamina la evaluación.</p></article><article><h2>Reparar desde lo dañado</h2><p>Propaga la corrupción.</p></article><article><h2>Publicación destructiva</h2><p>Deja lectores sin versión.</p></article><article><h2>IA que siempre responde</h2><p>Inventa cuando falta evidencia.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Banco de fallos · Core 1.2</div><h1>La arquitectura se aprende cuando algo se rompe</h1><p class="lead">Se ejecutaron 300 pruebas locales: diez fallos, treinta repeticiones por escenario.</p><table><tr><th>Familia</th><th>Escenarios</th><th>Resultado final</th></tr><tr><td>Pérdida</td><td>Eliminación y corrupción parcial</td><td>30/30 cada uno</td></tr><tr><td>Orden</td><td>Duplicado y revisión obsoleta</td><td>30/30 cada uno</td></tr><tr><td>Interrupción</td><td>25 %, 50 % y 75 %</td><td>30/30 cada uno</td></tr><tr><td>Evolución</td><td>Esquema y catálogo</td><td>30/30 tras corregir migración</td></tr><tr><td>Seguridad</td><td>Fuga de ámbito</td><td>Cero cruces</td></tr></table><div class="note"><strong>Hallazgo.</strong> La primera corrida descubrió que el cambio de esquema no estaba modelado. Corregirlo antes de publicar fue parte del resultado, no un dato que ocultar.</div></section>
<section class="book-page"><div class="eyebrow">Rutas de lectura</div><h1>Seis maneras de comenzar</h1><div class="route-grid"><article><h2>Principiante</h2><p>Caso → Canónico → Ámbito → Proyección → Reconstrucción.</p></article><article><h2>Arquitectura</h2><p>Modelo → Core → Fronteras → Presupuesto → Retiro.</p></article><article><h2>NoSQL</h2><p>Identidad → Revisión → Versiones → Publicación.</p></article><article><h2>Minería</h2><p>Dato fechado → Conjunto → Partición → Manifiesto.</p></article><article><h2>IA</h2><p>Recuperación → Evidencia → Abstención → Auditoría.</p></article><article><h2>Conformidad</h2><p>Requisitos → Amenazas → P1–A1 → D1–D8.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Evidencia reproducible</div><h1>Primera réplica NoSQL de Core 1.0</h1><p class="lead">Se ejecutaron 180 corridas sobre PouchDB y LokiJS: dos motores documentales, tres escalas y treinta repeticiones por celda.</p><div class="concept-grid"><article><h2>P1</h2><p>Lecturas equivalentes; la proyección redujo la mediana en las seis celdas.</p></article><article><h2>P2</h2><p>Amplificación observada: dos escrituras por cambio proyectado.</p></article><article><h2>R1</h2><p>Reconstrucción total equivalente e idempotente.</p></article><article><h2>S1</h2><p>Cero documentos cruzados y rechazo sin ámbito.</p></article><article><h2>A1</h2><p>Manifiesto, procedencia y partición temporal verificables.</p></article><article><h2>Límite</h2><p>Evidencia embebida; no representa redes, regiones ni facturación administrada.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Estadística ampliada</div><h1>Leer más allá de la mediana</h1><p class="lead">Core 1.1 informa p50, p95, p99, desviación absoluta mediana e intervalos bootstrap del 95 %.</p><table><tr><th>Motor · N</th><th>R1 p50</th><th>R1 p95</th><th>IC95 de la mediana</th></tr><tr><td>LokiJS · 5 000</td><td>45,932 ms</td><td>50,859 ms</td><td>45,260–46,864 ms</td></tr><tr><td>PouchDB · 5 000</td><td>499,896 ms</td><td>521,530 ms</td><td>495,701–502,708 ms</td></tr></table><p>No se eliminaron valores atípicos. Se utilizaron 4 000 remuestras y semilla registrada. La réplica distribuida posterior conserva por separado sus versiones, parámetros y resultados, de modo que las cifras embebidas no se confundan con las obtenidas mediante servicios.</p><div class="note"><strong>Regla editorial.</strong> Código disponible no significa evidencia ejecutada; cada afirmación debe señalar motor, versión, protocolo y fecha.</div></section>
<section class="book-page"><div class="eyebrow">Réplica distribuida · Core 1.2</div><h1>La misma prueba en tres servicios NoSQL</h1><p class="lead">El archivo conserva 270 corridas históricas: MongoDB 8.0, CouchDB 3.4 y OpenSearch 2.19.3; tres escalas y treinta repeticiones por motor y escala.</p><table><tr><th>Motor · N</th><th>Canónico p50</th><th>Proyección p50</th><th>R1 p50</th></tr><tr><td>MongoDB 8.0 · 5 000</td><td>157,856 ms</td><td>129,272 ms</td><td>3 179,603 ms</td></tr><tr><td>CouchDB 3.4 · 5 000</td><td>4 298,485 ms</td><td>1 477,093 ms</td><td>12 844,488 ms</td></tr><tr><td>OpenSearch 2.19.3 · 5 000</td><td>450,837 ms</td><td>250,173 ms</td><td>2 998,821 ms</td></tr></table><div class="concept-grid"><article><h2>Estado</h2><p>El oráculo original aprobó P1, P2, R1, S1 y A1; deben repetirse con el arnés corregido.</p></article><article><h2>Aislamiento observado</h2><p>No se registraron cruces de ámbito en la muestra histórica.</p></article><article><h2>Comparación</h2><p>Las latencias describen este entorno; no son una clasificación universal de motores.</p></article><article><h2>Clasificación correcta</h2><p>Son evidencia histórica de portabilidad, no certificación vigente.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Transparencia experimental</div><h1>Un fallo de plataforma también es evidencia</h1><p class="lead">OpenSearch 3.2.0 con Java 24 terminó por un fallo nativo al ejecutarse bajo emulación x86_64. La réplica confirmatoria se realizó con OpenSearch 2.19.3 y Java 21.</p><div class="decision-grid"><section><h2>Lo que sí puede afirmarse</h2><ul><li>el adaptador superó las pruebas con OpenSearch 2.19.3;</li><li>el protocolo, los tamaños y las repeticiones quedaron registrados;</li><li>la incidencia y la sustitución de versión permanecen visibles.</li></ul></section><section class="avoid"><h2>Lo que no puede afirmarse</h2><ul><li>que OpenSearch 3.2.0 fue validado;</li><li>que una sola máquina representa producción;</li><li>que la comparación predice costos de nube o red.</li></ul></section></div><div class="note"><strong>Lección.</strong> La reproducibilidad no consiste en ocultar obstáculos, sino en separar con precisión lo ejecutado, lo fallido y lo pendiente.</div></section>
<section class="book-page"><div class="eyebrow">Seguridad por diseño</div><h1>Doce amenazas que una proyección debe enfrentar</h1><div class="decision-grid"><section><h2>Datos y ámbitos</h2><ul><li>confusión entre organizaciones;</li><li>edición directa del derivado;</li><li>repetición y revisión obsoleta;</li><li>manipulación de proyecciones;</li><li>eliminación incompleta;</li><li>dependencia del proveedor.</li></ul></section><section><h2>Publicación, analítica e IA</h2><ul><li>fallo durante publicación;</li><li>envenenamiento analítico;</li><li>recuperación no autorizada;</li><li>evidencia insuficiente;</li><li>herramientas excesivas;</li><li>pérdida de procedencia.</li></ul></section></div><div class="note"><strong>Límite.</strong> COBRIA complementa, pero no reemplaza, autenticación, cifrado, respaldo o consenso del motor.</div></section>
<section class="book-page"><div class="eyebrow">Mapa general</div><h1>Nueve familias, una arquitectura</h1><div class="family-map">${[...new Set(familyByPattern)].map((f,i)=>`<article><b>${String(i+1).padStart(2,'0')}</b><h2>${f}</h2><p>${familyByPattern.filter(x=>x===f).length} patrones</p></article>`).join('')}</div></section>
<section class="book-page"><div class="eyebrow">Ruta de aprendizaje</div><h1>Tres maneras de recorrer el atlas</h1><div class="route-grid"><article><h2>Ruta esencial</h2><p>Objeto canónico → Repositorio con ámbito → Catálogo versionado → Proyección de lectura → Reconstrucción total.</p></article><article><h2>Ruta analítica</h2><p>Dato fechado → Conjunto reproducible → Característica versionada → Partición sin fuga → Manifiesto.</p></article><article><h2>Ruta de IA</h2><p>Recuperación limitada → Abstención con evidencia → Herramienta gobernada → Auditoría narrativa.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Regla de lectura</div><h1>De la analogía a la prueba</h1><ol class="big-steps"><li><b>Observar.</b> Reconozca el problema en una consulta, incidente o decisión.</li><li><b>Delimitar.</b> Identifique autoridad, ámbito, revisión y consumidor.</li><li><b>Contratar.</b> Escriba qué debe ocurrir y cómo falla.</li><li><b>Instrumentar.</b> Conserve métricas y procedencia.</li><li><b>Desafiar.</b> Pruebe repetición, atraso, interrupción y acceso prohibido.</li><li><b>Retirar.</b> Simplifique cuando el beneficio desaparezca.</li></ol></section>
<section class="book-page"><div class="eyebrow">Vocabulario visual</div><h1>La metáfora del bosque documental</h1><p class="lead">Las raíces representan documentos canónicos; el tronco, contratos; las ramas, servicios; los nidos, proyecciones; los senderos, ámbitos; y los colibríes, eventos que transportan cambios.</p><div class="note">La metáfora ayuda a recordar, pero la evidencia decide. Ninguna ilustración sustituye el contrato, la métrica o la prueba.</div><h2>Fauna y flora</h2><p>Las escenas emplean colibríes, ranas, tucanes, mariposas, perezosos y dantas junto con paisajes de Coto Brus.</p></section>`;

const ecosystemManual = `<section class="book-page title-page"><div class="eyebrow">Parte nueva · Ecosistema COBRIA</div><h1>De programar funciones a diseñar sistemas</h1><p class="lead">Una ruta para personas que empiezan y para equipos que necesitan un lenguaje común.</p><div class="note">Core conserva sus invariantes NoSQL. Los manuales que siguen enseñan las decisiones de software que lo rodean.</div></section>
<section class="book-page"><div class="eyebrow">Mapa del ecosistema</div><h1>Once módulos conectados</h1><div class="family-map">${['Fundamentos','Layers','Pattern Design','Data','Core','Quality','Operations','IA y analítica','Build','Evidencia','Engineering'].map((name,index)=>`<article><b>${String(index+1).padStart(2,'0')}</b><h2>${name}</h2><p>${['Lenguaje común','Responsabilidades','Soluciones recurrentes','Persistencia','Invariantes','Pruebas','Recuperación','Procedencia','Aplicación completa','Resultados y límites','Industrialización'][index]}</p></article>`).join('')}</div></section>
<section class="book-page"><div class="eyebrow">Manual de capas</div><h1>Una dirección clara para las dependencias</h1><table><tr><th>Capa</th><th>Responsabilidad</th><th>No debe</th></tr><tr><td>Presentación</td><td>Traducir HTTP, interfaz o consola</td><td>Decidir reglas del dominio</td></tr><tr><td>Aplicación</td><td>Coordinar un caso de uso</td><td>Conocer detalles del motor</td></tr><tr><td>Dominio</td><td>Proteger identidad e invariantes</td><td>Depender de marcos externos</td></tr><tr><td>Puertos</td><td>Declarar capacidades necesarias</td><td>Fijar un proveedor</td></tr><tr><td>Infraestructura</td><td>Implementar persistencia y servicios</td><td>Redefinir el negocio</td></tr></table><div class="note"><strong>Regla práctica.</strong> Las decisiones del centro no dependen de los detalles de afuera.</div></section>
<section class="book-page"><div class="eyebrow">Traducción del código real</div><h1>Objeto, Dater, Service y Catalog</h1><div class="concept-grid"><article><h2>Object</h2><p>Entidad u objeto de valor que protege reglas.</p></article><article><h2>Dater</h2><p>Nombre local para una combinación de repositorio, mapeador y serializador. No es un término universal.</p></article><article><h2>Service</h2><p>Servicio de aplicación o dominio que coordina una decisión.</p></article><article><h2>Catalog</h2><p>Vocabulario o dato de referencia con versión y vigencia.</p></article><article><h2>Indexer</h2><p>Constructor de una proyección o modelo de lectura.</p></article><article><h2>Connect</h2><p>Adaptador o puerta de enlace hacia una capacidad externa.</p></article></div></section>
<section class="book-page"><div class="eyebrow">COBRIA Build</div><h1>Ejemplo ejecutable: observaciones de biodiversidad</h1><p>La entidad canónica exige identidad, ámbito, especie, cantidad, revisión y fecha. El caso de uso autoriza antes de acceder, detecta repeticiones y delega la persistencia a un puerto.</p><pre>const resultado = await registrar.ejecutar({
  id: "obs-001",
  ambito: "reserva-sur",
  especie: "colibri",
  cantidad: 3,
  revision: 1,
  observadaEn: "2026-09-04T14:00:00Z"
}, contextoAutorizado);</pre><div class="note"><strong>Resultado observable.</strong> Repetir la misma clave y entrada no duplica. Reutilizarla con otra entrada falla.</div></section>
<section class="book-page"><div class="eyebrow">Pruebas de la aplicación</div><h1>Seis comportamientos antes que seis tecnologías</h1><ol class="big-steps"><li>Registra un documento canónico válido.</li><li>Rechaza otro ámbito antes de tocar el repositorio.</li><li>Repite sin duplicar mediante idempotencia.</li><li>Rechaza una clave reutilizada con contenido distinto.</li><li>Impide que una revisión obsoleta reemplace el presente.</li><li>Retira y reconstruye una proyección equivalente.</li></ol><div class="note"><strong>Ejecución.</strong> El paquete replication/examples/ecosistema-app funciona con Node.js y no requiere dependencias externas.</div></section>
<section class="book-page"><div class="eyebrow">Bases de datos</div><h1>Elegir forma desde acceso, cambio y consistencia</h1><div class="decision-grid"><section><h2>Incrustar</h2><p>Cuando los datos se leen y cambian juntos, comparten ciclo de vida y caben bajo límites razonables.</p></section><section><h2>Referenciar</h2><p>Cuando una entidad tiene vida propia, cardinalidad grande o actualización independiente.</p></section><section><h2>Proyectar</h2><p>Cuando una lectura importante necesita otra forma y el beneficio medido supera el costo total.</p></section><section><h2>Versionar</h2><p>Cuando el significado cambia y lectores antiguos deben convivir con documentos nuevos.</p></section></div></section>
<section class="book-page"><div class="eyebrow">Quality y Operations</div><h1>Terminado significa verificable y recuperable</h1><div class="reference-grid"><section><h2>Calidad</h2><ul><li>pruebas unitarias del dominio;</li><li>pruebas de contrato por puerto;</li><li>casos negativos de seguridad;</li><li>equivalencia de reconstrucción;</li><li>métricas de costo y frescura.</li></ul></section><section><h2>Operación</h2><ul><li>respaldo probado;</li><li>publicación por versión;</li><li>procedimiento de reconstrucción;</li><li>límites de capacidad;</li><li>registro de decisiones e incidentes.</li></ul></section></div></section>
<section class="book-page"><div class="eyebrow">COBRIA Engineering</div><h1>Del diseño a una operación confiable</h1><p class="lead">Ocho contratos conectan la experiencia del usuario con la autoridad, la entrega y el mantenimiento.</p><div class="concept-grid"><article><h2>Estado operativo</h2><p>Reposo, carga, éxito, vacío, error y reintento visibles; un efecto por intención.</p></article><article><h2>Autoridad</h2><p>Actor, capacidad y ámbito se derivan en una frontera confiable.</p></article><article><h2>Resiliencia</h2><p>Offline seguro, límites, reintentos y dead-letter sin repetición ciega.</p></article><article><h2>Entrega</h2><p>Un digest recorre preview, staging y producción con rollback.</p></article><article><h2>Observabilidad</h2><p>Telemetría privada, acotada y no bloqueante.</p></article><article><h2>Evolución</h2><p>El legado deja de crecer y pierde consumidores hasta retirarse.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Laboratorio Engineering</div><h1>Promoción ligada al artefacto</h1><p>Imagine un sistema comunitario que publica una nueva lectura de observaciones. La compilación genera un digest único; staging ensaya acceso autorizado, rechazo cruzado y reconstrucción; producción recibe exactamente el mismo artefacto.</p><pre>commit → pruebas → artefacto inmutable
→ preview → staging → aprobación
→ producción → humo → observación</pre><div class="decision-grid"><section><h2>Compruebe</h2><ul><li>SHA y digest coinciden;</li><li>respaldo verificable;</li><li>caso positivo y denegación;</li><li>rollback disponible.</li></ul></section><section class="avoid"><h2>Rechace</h2><ul><li>recompilar para producción;</li><li>editar el gate a mano;</li><li>copiar datos personales a staging;</li><li>declarar GO sin evidencia.</li></ul></section></div><div class="note"><strong>Costo.</strong> La disciplina añade almacenamiento, pruebas y tiempo de promoción; reduce diferencias invisibles entre lo probado y lo publicado.</div></section>
<section class="book-page"><div class="eyebrow">Piloto de adopción · Fase 21</div><h1>Encontrar evidencia no equivale a validar producción</h1><p class="lead">La rúbrica Engineering se aplicó a un commit limpio de un sistema comercial existente.</p><div class="decision-grid"><section><h2>Resultado estructural</h2><p>Los ocho contratos poseen archivos, pruebas o decisiones rastreables, y cada evidencia quedó ligada a una huella SHA-256.</p><strong>8/8 con evidencia estructural</strong></section><section class="avoid"><h2>Límite operacional</h2><p>No se ejecutaron staging, producción, rollback, accesibilidad con personas ni transferencia independiente.</p><strong>0 presentados como validados operacionalmente</strong></section></div><h2>Lección</h2><p>La utilidad del piloto no está en producir una calificación perfecta. Está en separar con precisión lo que puede inspeccionarse en un repositorio de lo que debe observarse en ambientes y con personas.</p><div class="note"><strong>Reproducibilidad.</strong> El gate reconstruye el commit congelado en un checkout temporal y compara rutas, términos y huellas sin alterar el proyecto observado.</div></section>
<section class="book-page"><div class="eyebrow">Fase 22 · Manifiesto de adopción</div><h1>Declarar para verificar</h1><p class="lead">El evaluador ya no conoce carpetas particulares. Cada equipo publica un mapa mínimo de evidencias para los ocho contratos Engineering.</p><pre>{
  "project": { "ref": "commit-inmutable" },
  "contracts": [{
    "id": "ENG-001",
    "owner": "producto",
    "evidence": [{ "path": "...", "containsAll": ["..."] }]
  }]
}</pre><div class="decision-grid"><section><h2>Protecciones</h2><ul><li>lectura desde objetos Git;</li><li>huellas SHA-256;</li><li>rutas relativas sin escape;</li><li>ocho IDs únicos;</li><li>remoto y commit opcionalmente fijados.</li></ul></section><section class="avoid"><h2>No demuestra</h2><ul><li>que el comportamiento sea correcto;</li><li>que producción esté disponible;</li><li>que el control sea suficiente;</li><li>que una persona pueda transferirlo.</li></ul></section></div><div class="note"><strong>Resultado.</strong> El mismo manifiesto reprodujo 8/8 evidencias estructurales y mantuvo cero validaciones operacionales.</div></section>
<section class="book-page"><div class="eyebrow">IA y analítica</div><h1>Una predicción sin procedencia es difícil de defender</h1><p class="lead">Documentos, índices, vectores y conjuntos analíticos cumplen papeles distintos. COBRIA exige conservar el hilo que permite volver del resultado a la fuente autorizada.</p><ol class="steps"><li>Separar por entidad, tiempo y ámbito antes de entrenar.</li><li>Versionar características, parámetros y cortes.</li><li>Recuperar únicamente evidencia autorizada.</li><li>Abstenerse cuando la cobertura sea insuficiente.</li><li>Guardar un manifiesto que permita reproducir el resultado.</li></ol></section>
<section class="book-page"><div class="eyebrow">Criterio de terminado</div><h1>La revisión que puede hacer otra persona</h1><div class="rubric">${['La responsabilidad de cada capa está escrita','El vocabulario del dominio es consistente','Los patrones responden a tensiones reales','La persistencia protege ámbito y revisión','Las pruebas cubren éxito y rechazo','La recuperación fue ensayada','La IA conserva procedencia','Otra persona puede ejecutar el ejemplo'].map(x=>`<div><span>${x}</span><b>Sí · No</b></div>`).join('')}</div><div class="note">Si una respuesta es “no”, el siguiente paso ya está identificado.</div></section>`;

const phase23Page = `<section class="book-page"><div class="eyebrow">Fase 23 · Transferencia estructural</div><h1>Comparar sin clasificar</h1><p class="lead">Una misma rúbrica inspeccionó commits congelados de tres sistemas con dominios y estructuras diferentes.</p><table><tr><th>Proyecto</th><th>Evidencia estructural</th><th>Operacional</th></tr><tr><td>POS Guápiles</td><td>8/8</td><td>0</td></tr><tr><td>CRMHotel</td><td>5/8</td><td>0</td></tr><tr><td>BSHandball</td><td>4/8</td><td>0</td></tr></table><div class="decision-grid"><section><h2>Qué aprendemos</h2><p>Estado, autoridad y control del legado dejaron evidencia reconocible en los tres repositorios.</p></section><section class="avoid"><h2>Qué no concluimos</h2><p>Una brecha no prueba incumplimiento y la cobertura no mide calidad, madurez ni rendimiento.</p></section></div><div class="note"><strong>Siguiente prueba.</strong> Equipos independientes deben redactar los manifiestos y revisar semánticamente cada coincidencia.</div></section>`;

const phase24Page = `<section class="book-page"><div class="eyebrow">Fase 24 · Revisión semántica</div><h1>La independencia no se simula</h1><p class="lead">La coincidencia de rutas y palabras se transforma en una pregunta para personas ajenas al diseño.</p><div class="concept-grid"><article><h2>3 muestras</h2><p>Identidades M-01, M-02 y M-03 separadas de la clave del coordinador.</p></article><article><h2>2 revisores</h2><p>Trabajo independiente, conflictos declarados y código seudónimo.</p></article><article><h2>8 decisiones</h2><p>Respaldado, no respaldado o evidencia insuficiente, con justificación.</p></article><article><h2>Acuerdo</h2><p>Porcentaje observado y kappa de Cohen, sin borrar discrepancias.</p></article><article><h2>Adjudicación</h2><p>Una tercera persona revisa desacuerdos después del cierre.</p></article><article><h2>Estado</h2><p>0/6 respuestas humanas; infraestructura preparada, estudio pendiente.</p></article></div><div class="note"><strong>Integridad científica.</strong> Los perfiles sintéticos prueban el software, pero jamás cuentan como revisores ni evidencia externa.</div></section>`;

const phase25Page = `<section class="book-page"><div class="eyebrow">Fase 25 · Calibración</div><h1>Evidencia por dimensión</h1><p class="lead">Una coincidencia textual no demuestra un contrato completo.</p><div class="concept-grid"><article><h2>Frontera</h2><p>El legado está aislado y sus consumidores conocen el límite.</p></article><article><h2>No crecimiento</h2><p>Una regla ejecutable impide aumentar tamaño o responsabilidades.</p></article><article><h2>Retiro</h2><p>Existe una condición, métrica o ruta para eliminarlo.</p></article></div><table><tr><th>Caso</th><th>Dimensiones</th><th>Lectura</th></tr><tr><td>M-01</td><td>3/3</td><td>Respaldado estructuralmente</td></tr><tr><td>M-02</td><td>2/3</td><td>Evidencia insuficiente</td></tr><tr><td>M-03</td><td>3/3</td><td>Respaldado estructuralmente</td></tr></table><div class="note"><strong>Alcance.</strong> Es una calibración de la propuesta, no certificación oficial ni validación de producción.</div></section>`;

const phase26Page = `<section class="book-page"><div class="eyebrow">Fase 26 · Rúbrica general</div><h1>Ocho contratos, veinticuatro dimensiones</h1><p class="lead">Cada contrato Engineering se evalúa mediante tres condiciones que deben aparecer juntas.</p><div class="concept-grid"><article><h2>Experiencia</h2><p>Estados, transiciones y recuperación.</p></article><article><h2>Autoridad</h2><p>Contexto confiable, efecto único y salida trazable.</p></article><article><h2>Resiliencia</h2><p>Política, reintento acotado y recuperación visible.</p></article><article><h2>Entrega</h2><p>Artefacto inmutable, gates y rollback.</p></article><article><h2>Operación</h2><p>Privacidad, límites y comportamiento no bloqueante.</p></article><article><h2>Evolución</h2><p>Medición, presupuesto, legado e incidentes reutilizables.</p></article></div><div class="note"><strong>Plantilla honesta.</strong> Empieza con 24 decisiones nulas. No evaluado no significa incumplimiento y ninguna salida constituye certificación.</div></section>`;

const phase27Page = `<section class="book-page"><div class="eyebrow">Fase 27 · Expediente comparativo</div><h1>Setenta y dos preguntas, ninguna respuesta inventada</h1><p class="lead">Tres proyectos por ocho contratos por tres dimensiones producen una cola explícita de revisión semántica.</p><div class="decision-grid"><section><h2>Lo que conserva</h2><ul><li>commit congelado;</li><li>ruta y huella del archivo;</li><li>términos observados;</li><li>criterio dimensional;</li><li>razón de revisión.</li></ul></section><section class="avoid"><h2>Lo que no produce</h2><ul><li>ranking de proyectos;</li><li>porcentaje de calidad;</li><li>certificación oficial;</li><li>validación operacional;</li><li>juicio automático.</li></ul></section></div><table><tr><th>Unidad</th><th>Cantidad</th><th>Estado inicial</th></tr><tr><td>Proyectos</td><td>3</td><td>Commits congelados</td></tr><tr><td>Contratos observados</td><td>24</td><td>Evidencia candidata</td></tr><tr><td>Decisiones dimensionales</td><td>72</td><td>Pendientes</td></tr></table><div class="note"><strong>Principio.</strong> La automatización reúne evidencia; la interpretación debe justificar cada dimensión.</div></section>`;

const phase28Page = `<section class="book-page"><div class="eyebrow">Fase 28 · Revisión ciega</div><h1>Independencia antes que acuerdo</h1><p class="lead">Dos personas examinan el mismo material sin conocer la identidad de las muestras ni las respuestas de la otra.</p><div class="concept-grid"><article><h2>3 muestras</h2><p>Seudónimos M-01, M-02 y M-03; la clave queda fuera.</p></article><article><h2>24 dimensiones</h2><p>Criterio y ejemplo insuficiente para cada contrato.</p></article><article><h2>2 revisores</h2><p>Formularios iguales, trabajo separado y conflictos declarados.</p></article><article><h2>144 juicios</h2><p>Decisión, confianza y justificación por cada dimensión.</p></article><article><h2>0 precargados</h2><p>Ninguna respuesta o atestación se inventa.</p></article><article><h2>Acuerdo posterior</h2><p>Solo se calcula cuando ambos formularios estén completos.</p></article></div><div class="note"><strong>Límite.</strong> El instrumento está preparado; la revisión humana continúa pendiente y no constituye certificación.</div></section>`;

const phase29Page = `<section class="book-page"><div class="eyebrow">Fase 29 · Ingesta y acuerdo</div><h1>Sin respuestas, la métrica correcta es nula</h1><p class="lead">El sistema distingue entre estar preparado para calcular y haber recibido evidencia humana suficiente.</p><div class="decision-grid"><section><h2>Antes del cálculo</h2><ul><li>dos revisores distintos;</li><li>72 dimensiones alineadas;</li><li>atestación humana;</li><li>trabajo independiente;</li><li>conflictos declarados.</li></ul></section><section><h2>Después del cálculo</h2><ul><li>acuerdo observado;</li><li>acuerdo esperado;</li><li>kappa de Cohen;</li><li>distribución por decisión;</li><li>desacuerdos íntegros.</li></ul></section></div><table><tr><th>Estado actual</th><th>Valor</th></tr><tr><td>Respuestas recibidas</td><td>0 de 2</td></tr><tr><td>Juicios pareados</td><td>0</td></tr><tr><td>Acuerdo y kappa</td><td>No calculados</td></tr><tr><td>Certificación oficial</td><td>No</td></tr></table><div class="note"><strong>Propuesta independiente.</strong> Incluso con respuestas completas, el acuerdo mediría consistencia entre revisores, no verdad universal ni certificación.</div></section>`;

const phase30Page = `<section class="book-page"><div class="eyebrow">Fase 30 · Adjudicación</div><h1>Resolver no significa borrar</h1><p class="lead">La tercera mirada interviene únicamente donde dos revisores auténticos discrepan.</p><div class="decision-grid"><section><h2>Entrada protegida</h2><ul><li>clave dimensional;</li><li>decisión del revisor A;</li><li>decisión del revisor B;</li><li>evidencia ya examinada;</li><li>acuerdo previo intacto.</li></ul></section><section><h2>Salida trazable</h2><ul><li>decisión adjudicada;</li><li>justificación específica;</li><li>atestación humana;</li><li>conflicto descartado;</li><li>identidad distinta del par.</li></ul></section></div><table><tr><th>Estado actual</th><th>Valor</th></tr><tr><td>Par de revisión disponible</td><td>No</td></tr><tr><td>Desacuerdos disponibles</td><td>0</td></tr><tr><td>Adjudicaciones completas</td><td>0</td></tr><tr><td>Certificación oficial</td><td>No</td></tr></table><div class="note"><strong>Propuesta independiente.</strong> El mecanismo está listo; no se inventan discrepancias ni una tercera persona para aparentar validación.</div></section>`;

const phase31Page = `<section class="book-page"><div class="eyebrow">Fase 31 · Operación controlada</div><h1>Preparar el fallo antes de provocarlo</h1><p class="lead">Un ensayo operacional necesita hipótesis, límites y evidencia antes de tocar un ambiente.</p><div class="concept-grid"><article><h2>Rollback</h2><p>Mismo digest, humo verificable y regreso al estado anterior.</p></article><article><h2>Reintentos</h2><p>Efecto único, espera acotada y dead-letter observable.</p></article><article><h2>Telemetría</h2><p>Sanitización, límites y negocio no bloqueado.</p></article><article><h2>Reconstrucción</h2><p>Fuente declarada, candidata equivalente y publicación segura.</p></article><article><h2>Ámbito</h2><p>Acceso cruzado rechazado antes del almacén.</p></article><article><h2>Aborto</h2><p>Cada escenario define cuándo detenerse sin improvisar.</p></article></div><table><tr><th>Estado actual</th><th>Valor</th></tr><tr><td>Escenarios preparados</td><td>5</td></tr><tr><td>Escenarios ejecutados</td><td>0</td></tr><tr><td>Ambiente autorizado usado</td><td>No</td></tr><tr><td>Certificación oficial</td><td>No</td></tr></table><div class="note"><strong>Propuesta independiente.</strong> Una plantilla completa no equivale a una corrida: la evidencia operacional sigue pendiente.</div></section>`;

const phase32Page = `<section class="book-page"><div class="eyebrow">Fase 32 · Réplica externa</div><h1>Otra computadora, otra persona</h1><p class="lead">La reproducibilidad exige salir del equipo y del conocimiento tácito del autor.</p><ol class="big-steps"><li>Instalación limpia.</li><li>Pruebas de la réplica científica.</li><li>Aplicación neutral.</li><li>Construcción del sitio.</li><li>Reconstrucción editorial.</li></ol><div class="note"><strong>Estado.</strong> Cinco tareas preparadas, cero repeticiones externas recibidas y ninguna certificación.</div></section>`;
const phase33Page = `<section class="book-page"><div class="eyebrow">Fase 33 · Síntesis</div><h1>Lo ausente permanece ausente</h1><p class="lead">Una síntesis rigurosa no rellena celdas con expectativas.</p><div class="concept-grid"><article><h2>Disponible</h2><p>Contratos, herramientas, gates y pruebas locales.</p></article><article><h2>Pendiente</h2><p>Revisión humana independiente.</p></article><article><h2>Pendiente</h2><p>Ejecución operacional autorizada.</p></article><article><h2>Pendiente</h2><p>Repetición en otra computadora.</p></article></div><div class="note"><strong>Límite.</strong> Efectos e intervalos externos continúan nulos; no se infieren.</div></section>`;
const phase34Page = `<section class="book-page"><div class="eyebrow">Fase 34 · Sincronización editorial</div><h1>Cuatro productos, un mismo estado</h1><p class="lead">Artículo, documento maestro, libro y sitio no deben contar historias distintas.</p><table><tr><th>Producto</th><th>Puede explicar</th><th>No puede afirmar</th></tr><tr><td>Artículo</td><td>Contribución y evidencia local</td><td>Validación externa inexistente</td></tr><tr><td>Maestro</td><td>Método y limitaciones</td><td>Resultados humanos inventados</td></tr><tr><td>Libro</td><td>Enseñanza y aplicación</td><td>Norma universal</td></tr><tr><td>Sitio</td><td>Exploración y recursos</td><td>Certificación oficial</td></tr></table><div class="note"><strong>Estado.</strong> Instantánea común sincronizada con cero evidencia externa atribuida.</div></section>`;
const phase35Page = `<section class="book-page"><div class="eyebrow">Fase 35 · Candidato local</div><h1>Huellas antes que etiquetas</h1><p class="lead">Un candidato reproducible identifica exactamente qué fuentes lo componen.</p><div class="decision-grid"><section><h2>Incluye</h2><ul><li>rutas;</li><li>tamaños;</li><li>SHA-256;</li><li>estado de propuesta;</li><li>comandos de verificación.</li></ul></section><section class="avoid"><h2>No incluye</h2><ul><li>firma inventada;</li><li>release oficial;</li><li>publicación remota;</li><li>DOI ficticio;</li><li>certificación.</li></ul></section></div><div class="note"><strong>Estado.</strong> Candidato local construido, no firmado y no publicado.</div></section>`;
const phase36Page = `<section class="book-page"><div class="eyebrow">Fase 36 · Publicación responsable</div><h1>Preparar no es publicar</h1><p class="lead">La última puerta enumera la autoridad que todavía falta.</p><div class="rubric">${['Revisión humana independiente','Corrida operacional autorizada','Réplica externa','Firma de release','Depósito público o DOI'].map(x=>`<div><span>${x}</span><b>Pendiente</b></div>`).join('')}</div><div class="note"><strong>Propuesta independiente.</strong> Estado: preparada, no publicada. Solo una persona o servicio autorizado puede completar estos actos.</div></section>`;

const cases = [
  ['Reservas y servicios','Una organización administra alojamientos, disponibilidad, servicios y cobros documentales.','Objeto canónico, Catálogo versionado, Proyección de lectura, Cola de salida transaccional, Ventana de frescura declarada'],
  ['Seguimiento deportivo','Un programa registra sesiones, planteles, métricas fechadas y análisis longitudinal.','Dato fechado, Repositorio con ámbito, Conjunto reproducible, Característica versionada, Partición sin fuga'],
  ['Gestión territorial comunitaria','Equipos de campo documentan solicitudes, visitas, evidencia y decisiones con acceso delimitado.','Identidad estable, Validación en frontera, Auditoría narrativa, Recuperación limitada y Abstención con evidencia']
].map((c,i)=>`<section class="book-page case-cover"><div class="eyebrow">Caso guiado ${i+1}</div><h1>${c[0]}</h1><p class="lead">${c[1]}</p><div class="note"><strong>Patrones principales.</strong> ${c[2]}.</div></section><section class="book-page"><div class="eyebrow">Caso ${i+1} · Diseño</div><h1>Del lenguaje del dominio al documento</h1><h2>Decisiones</h2><ol class="steps"><li>Definir identidad y ámbito antes de elegir colecciones.</li><li>Separar hechos históricos de estados reemplazables.</li><li>Versionar vocabularios y contratos desde la primera migración.</li><li>Diseñar cada proyección desde una consulta concreta.</li></ol><h2>Documento mínimo</h2><pre>{ identidad, ámbito, revisión, contrato, datos, procedencia }</pre><div class="note">La forma final cambia con el dominio; los campos de gobierno permanecen verificables.</div></section><section class="book-page"><div class="eyebrow">Caso ${i+1} · Fallos</div><h1>Ensayo de degradación</h1><table><tr><th>Fallo</th><th>Respuesta esperada</th></tr><tr><td>Evento duplicado</td><td>Un solo efecto por revisión</td></tr><tr><td>Proyección atrasada</td><td>Frescura visible y degradación declarada</td></tr><tr><td>Ámbito manipulado</td><td>Rechazo antes de recuperar documentos</td></tr><tr><td>Cambio incompatible</td><td>Nueva versión y convivencia controlada</td></tr></table><h2>Evidencia</h2><p>Guarde manifiesto, entradas, revisión inicial y final, métricas, caso negativo y procedimiento de reversión.</p></section><section class="book-page"><div class="eyebrow">Caso ${i+1} · Revisión</div><h1>Preguntas para el equipo</h1><div class="question-grid"><p>¿Dónde vive la única autoridad de cambio?</p><p>¿Qué copia puede borrarse hoy?</p><p>¿Qué lectura tolera atraso y cuánto?</p><p>¿Qué dato no debe cruzar un ámbito?</p><p>¿Cómo se reproduce una cifra analítica?</p><p>¿Qué mecanismo podría retirarse?</p></div><div class="note"><strong>Cierre.</strong> El caso termina cuando otra persona puede reconstruir la decisión sin preguntarle al autor.</div></section>`).join('');

const workshop = `<section class="book-page"><div class="eyebrow">Taller práctico</div><h1>Construya una arquitectura COBRIA</h1><p class="lead">Ocho estaciones convierten un problema real en un diseño verificable. Trabaje con una muestra pequeña y conserve cada decisión.</p></section>${['Inventario de decisiones y consumidores','Diseño de documentos e identidad','Contratos, ámbito y validación','Catálogos y evolución semántica','Proyecciones e índices','Reconstrucción, eventos y reparación','Minería de datos e inteligencia artificial','Evaluación, costos y retiro'].map((x,i)=>`<section class="book-page"><div class="eyebrow">Estación ${i+1} de 8</div><h1>${x}</h1><h2>Producto de la estación</h2><p>${['Mapa de escrituras, lecturas, responsables y consecuencias.','Tres documentos con identidad, revisión, tiempos y procedencia.','Contrato de éxito, rechazo y acceso prohibido.','Una entrada versionada con vigencia, sustitución y cuarentena.','Ficha de consulta con filtros, orden, salida, frescura y presupuesto.','Manifiesto y prueba de equivalencia incremental frente a total.','Partición sin fuga, definición versionada y política de abstención.','Tabla comparativa, umbrales, rúbrica y procedimiento de retiro.'][i]}</p><h2>Trabajo</h2><ol class="steps"><li>Describa el estado inicial con un ejemplo concreto.</li><li>Escriba el contrato antes de implementar.</li><li>Diseñe un caso feliz y dos negativos.</li><li>Defina la evidencia que conservará.</li><li>Revise con una persona que no participó en el diseño.</li></ol><div class="note"><strong>Criterio de avance.</strong> No continúe si la autoridad, el ámbito o la evidencia siguen implícitos.</div></section>`).join('')}`;

const glossaryTerms = [['Autoridad','Lugar autorizado para aceptar un cambio legítimo.'],['Ámbito','Límite organizacional o de seguridad que acompaña toda operación.'],['Canónico','Documento desde el cual los derivados pueden volver a producirse.'],['Catálogo','Vocabulario versionado que estabiliza significado.'],['Contrato','Condición observable de entrada, resultado y fallo.'],['Corte','Punto temporal o de revisión usado para reproducir un conjunto.'],['Derivado','Representación orientada a una lectura, analítica o IA.'],['Frescura','Edad observable de una proyección frente a su fuente.'],['Idempotencia','Propiedad por la cual repetir no añade efectos distintos.'],['Linaje','Enlaces entre fuente, transformación, versión y resultado.'],['Manifiesto','Registro sellado de materiales y parámetros de construcción.'],['Procedencia','Origen y transformación documentados de un dato.'],['Proyección','Derivado diseñado para una necesidad concreta.'],['Reconstrucción','Producción repetible de un derivado desde fuentes autorizadas.'],['Revisión','Número o marca monotónica que evita regresiones silenciosas.'],['Tiempo conocido','Momento en que el sistema aprendió un hecho.'],['Tiempo válido','Momento del mundo al que el hecho se refiere.'],['Ventana','Atraso máximo aceptado por una lectura.']];
const glossary = Array.from({length:6},(_,page)=>`<section class="book-page"><div class="eyebrow">Glosario ilustrado · ${page+1}/6</div><h1>Lenguaje COBRIA</h1>${glossaryTerms.slice(page*3,page*3+3).map(t=>`<article class="term"><h2>${t[0]}</h2><p>${t[1]}</p><small>Pregunta: ¿dónde puede observarse y cómo se prueba?</small></article>`).join('')}</section>`).join('');

const bibliography = `<section class="book-page bibliographic-page"><div class="eyebrow">Fuentes y antecedentes</div><h1>Bibliografía seleccionada</h1><p>Estas obras permiten situar COBRIA frente a patrones de diseño, diseño dirigido por el dominio, sistemas de datos y bases NoSQL. Las referencias se presentan conforme a la estructura autor-fecha-título-fuente de APA 7.</p><p class="apa-reference">American Psychological Association. (2020). <em>Publication manual of the American Psychological Association</em> (7th ed.).</p><p class="apa-reference">Evans, E. (2003). <em>Domain-driven design: Tackling complexity in the heart of software</em>. Addison-Wesley.</p><p class="apa-reference">Fowler, M. (2002). <em>Patterns of enterprise application architecture</em>. Addison-Wesley.</p><p class="apa-reference">Gamma, E., Helm, R., Johnson, R., &amp; Vlissides, J. (1994). <em>Design patterns: Elements of reusable object-oriented software</em>. Addison-Wesley.</p><p class="apa-reference">Kleppmann, M. (2017). <em>Designing data-intensive applications: The big ideas behind reliable, scalable, and maintainable systems</em>. O'Reilly Media.</p><p class="apa-reference">Sadalage, P. J., &amp; Fowler, M. (2012). <em>NoSQL distilled: A brief guide to the emerging world of polyglot persistence</em>. Addison-Wesley.</p><div class="note"><strong>Criterio editorial.</strong> Una fuente incluida aquí debe aparecer cuando sustenta una afirmación del texto; a su vez, toda cita del texto debe tener su entrada completa en la bibliografía.</div></section>`;

const themePath = path.join(import.meta.dirname, 'theme.css');
const previousHtml = path.join(import.meta.dirname, 'index.html');
const theme = fs.existsSync(themePath)
  ? fs.readFileSync(themePath, 'utf8')
  : (fs.readFileSync(previousHtml, 'utf8').match(/<style>([\s\S]*?)<\/style>/) ?? [null, ''])[1];
if (!theme.trim()) throw new Error('No existe un tema CSS externo ni incorporado para reconstruir el libro.');
const document = ({title, subtitle, body, coverImage = 'assets/ecosistema-cobria-sin-felinos-v3.png'}) => `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="author" content="${author}"><meta name="description" content="${subtitle}"><title>${title}</title><style>${theme}</style></head><body>
<section class="cover"><img src="${coverImage}" alt="Ecosistema COBRIA ilustrado"><div class="cover-title"><div class="kicker">Edición ecosistema ${ecosystemVersion}</div><h1>COBRIA</h1><h2>${subtitle}</h2></div><div class="cover-author">${author}<br>${place} · ${year}</div><div class="edition-chip">Propuesta independiente · ${ecosystemVersion}</div></section>
${body}
</body></html>`;

const decisionIndex = `<section class="book-page"><div class="eyebrow">Índice de decisiones</div><h1>¿Por dónde comienzo?</h1><table><tr><th>Necesidad</th><th>Primer patrón</th></tr><tr><td>No sé cuál copia contiene la verdad</td><td>Objeto canónico</td></tr><tr><td>Se cruzan organizaciones o permisos</td><td>Repositorio con ámbito</td></tr><tr><td>Los códigos cambian de significado</td><td>Catálogo versionado</td></tr><tr><td>Una consulta exige otra forma</td><td>Índice antes que proyección</td></tr><tr><td>No puedo rehacer una copia</td><td>Reconstrucción total</td></tr><tr><td>Las cifras no se reproducen</td><td>Conjunto de datos reproducible</td></tr><tr><td>La IA responde sin sustento</td><td>Abstención con evidencia</td></tr></table></section>`;
const finalRubric = `<section class="book-page"><div class="eyebrow">Rúbrica final</div><h1>Evaluación de una arquitectura COBRIA</h1><p>Califique de cero a dos: ausente, parcial o comprobado.</p><div class="rubric">${['Autoridad única','Ámbito obligatorio','Identidad estable','Revisión monotónica','Contrato versionado','Procedencia','Reconstrucción','Frescura observable','Caso negativo','Retiro seguro'].map(x=>`<div><span>${x}</span><b>0 · 1 · 2</b></div>`).join('')}</div><div class="note">Un cero en autoridad o aislamiento no se compensa con promedios altos.</div></section>`;
const closing = `<section class="closing"><div class="eyebrow">Cierre</div><h1>Diseñar también es dejar un camino de regreso</h1><p class="lead">COBRIA propone una disciplina sencilla de expresar y exigente de demostrar: una fuente autorizada, límites explícitos y derivados útiles que puedan explicarse, comprobarse, reconstruirse y retirarse.</p><p>El libro contiene treinta patrones, tres casos guiados y un glosario operativo. El cuaderno de trabajo reúne los laboratorios y las estaciones de práctica.</p><div class="note"><strong>Última pregunta.</strong> Si mañana desapareciera una proyección, ¿su equipo sabría reconstruirla sin inventar información?</div></section>`;

const html = document({title: 'COBRIA: patrones, capas, datos y software verificable', subtitle: 'Patrones, capas, datos y software verificable', body: `${frontMatter}
${ecosystemManual}
${cards}
${cases}${glossary}${decisionIndex}
${bibliography}
${closing}`});

const workbookHtml = document({title: 'COBRIA: cuaderno de trabajo', subtitle: 'Cuaderno de trabajo y laboratorios', coverImage: 'assets/taller-colaborativo-coto-brus-v1.png', body: `<section class="book-page title-page"><div class="eyebrow">Cuaderno de trabajo</div><h1>Aprender haciendo</h1><p class="lead">Ocho estaciones, treinta laboratorios y una rúbrica para documentar decisiones reales sin confundir práctica con certificación.</p><div class="note">Use copias o notas separadas. Este cuaderno acompaña al libro principal y no sustituye la especificación normativa.</div></section>${workshop}${finalRubric}${decisionIndex}`});

const technicalAnnexHtml = document({title: 'COBRIA: anexo técnico de trazabilidad', subtitle: 'Anexo técnico · evidencia, revisión y cierre', body: `<section class="book-page title-page"><div class="eyebrow">Anexo técnico</div><h1>Trazabilidad del programa de investigación</h1><p class="lead">Registro separado de transferencia, revisión, operación y preparación responsable. No forma parte del recorrido pedagógico principal.</p><div class="note"><strong>Estado.</strong> Propuesta independiente. Las actividades humanas o externas conservan el estado pendiente cuando no existe evidencia válida.</div></section>${phase23Page}${phase24Page}${phase25Page}${phase26Page}${phase27Page}${phase28Page}${phase29Page}${phase30Page}${phase31Page}${phase32Page}${phase33Page}${phase34Page}${phase35Page}${phase36Page}`});

fs.writeFileSync(path.join(import.meta.dirname, 'index.html'), html);
fs.writeFileSync(path.join(import.meta.dirname, 'cuaderno.html'), workbookHtml);
fs.writeFileSync(path.join(import.meta.dirname, 'anexo-tecnico.html'), technicalAnnexHtml);
const sitePublic = path.resolve(root, '..', 'COBRIA-atlas', 'public');
if (fs.existsSync(path.dirname(sitePublic))) {
  fs.mkdirSync(sitePublic, { recursive: true });
  const catalogo = patterns.map((p,index) => ({
    id: index + 1,
    slug: clean(p[0]).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),
    nombre: clean(p[0]), familia: familyByPattern[index], tipo: clean(p[1]), evidencia: clean(p[2]),
    proposito: clean(p[3]), problema: clean(p[4]), analogia: clean(p[5]), solucion: clean(p[6]),
    aplicacion: clean(p[7]), metricas: clean(p[8]), contrato: contracts[index], ejercicio: exercises[index],
    relaciones: related(index)
  }));
  fs.writeFileSync(path.join(sitePublic, 'catalogo.json'), JSON.stringify(catalogo, null, 2));
}
console.log(`Libro construido con ${patterns.length} fichas.`);
