import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
let tex = '';
if (!fs.existsSync(path.join(import.meta.dirname, 'index.html'))) {
  try { tex = fs.readFileSync(path.join(root, 'prelibro-catalogo-cobria.tex'), 'utf8'); }
  catch { tex = ''; }
}

function balanced(text, start) {
  let depth = 0;
  for (let i = start; i < text.length; i++) {
    if (text[i] === '{') depth++;
    if (text[i] === '}' && --depth === 0) return [text.slice(start + 1, i), i + 1];
  }
  throw new Error('Llave sin cierre');
}

const patterns = [];
let cursor = 0;
while ((cursor = tex.indexOf('\\Ficha{', cursor)) >= 0) {
  let at = cursor + '\\Ficha'.length;
  const fields = [];
  for (let i = 0; i < 9; i++) {
    while (/\s/.test(tex[at])) at++;
    const [value, next] = balanced(tex, at);
    fields.push(value); at = next;
  }
  patterns.push(fields); cursor = at;
}
if (patterns.length === 0) {
  const previous = fs.readFileSync(path.join(import.meta.dirname, 'index.html'), 'utf8');
  const strip = value => value.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
  for (const hit of previous.matchAll(/<article class="pattern[^>]*>([\s\S]*?)<\/article>/g)) {
    const block = hit[1];
    const title = strip((block.match(/<h1>([\s\S]*?)<\/h1>/)||[])[1]||'');
    const badges = [...block.matchAll(/<span class="badge">([\s\S]*?)<\/span>/g)].map(x=>strip(x[1]).replace(/^Evidencia:\s*/,''));
    const bodies = [...block.matchAll(/<section class="block[^>]*>[\s\S]*?<p>([\s\S]*?)<\/p><\/section>/g)].map(x=>strip(x[1]));
    if (title && badges.length === 2 && bodies.length === 6) patterns.push([title,...badges,...bodies]);
  }
}

const nuevasFichas = [
  ['Identidad documental estable','Adaptación COBRIA','Identidad y migración','Mantener una identidad independiente de ubicación, forma y proveedor.','Claves derivadas de rutas, nombres visibles o posiciones cambian durante una migración y rompen referencias.','Como el número de una muestra de campo: la etiqueta continúa aunque cambie de caja o estante.','Asigne una identidad opaca dentro del ámbito; trate claves externas como atributos versionados y valide colisiones en la frontera.','Úselo cuando un documento sobreviva importaciones, fusiones o cambios de colección. Evite codificar significado mutable en la identidad.','Mida colisiones, referencias huérfanas y tiempo de resolución. Se relaciona con Objeto canónico, Revisión obsoleta rechazada y Catálogo versionado.'],
  ['Validación en frontera','Patrón establecido','Contrato verificable','Impedir que formas inválidas entren al núcleo documental.','Aceptar primero y corregir después dispersa supuestos y convierte cada lector en un validador distinto.','Como una estación biológica: cada muestra se registra y revisa antes de entrar al archivo.','La frontera comprueba forma, ámbito, revisión, vocabulario y reglas invariantes; devuelve errores estructurados sin escritura parcial.','Aplíquelo en API, importadores, consumidores y herramientas. Conserve el dato crudo separado cuando sea evidencia legítima.','Mida rechazos por causa, campos desconocidos y escrituras parciales. Se conecta con Contrato versionado y Herramienta de agente gobernada.'],
  ['Contrato documental versionado','Adaptación COBRIA','Compatibilidad demostrada','Evolucionar documentos sin exigir una migración instantánea de todo el conjunto.','Cambiar el significado de un campo bajo el mismo nombre produce lectores temporalmente incompatibles.','Como una guía de especies por ediciones: cada observación indica con qué edición fue clasificada.','Cada documento declara versión; lectores admiten un intervalo explícito y las transformaciones entre versiones son deterministas e idempotentes.','Úselo ante cambios aditivos o incompatibles. Mantenga pruebas de lectura hacia atrás y hacia delante durante la convivencia.','Mida documentos por versión, fallos de conversión y consumidores antiguos. Se relaciona con Catálogo versionado y Publicación por versión.'],
  ['Lectura coherente por revisión','Contrato compuesto','Consistencia observable','Evitar respuestas formadas por fragmentos de revisiones incompatibles.','Consultar varias proyecciones puede mezclar estados aunque cada lectura aislada sea correcta.','Como comparar fotografías de una misma parcela: todas deben pertenecer al mismo levantamiento.','Propague revisión objetivo o corte; acepte solo fragmentos compatibles y declare degradación cuando no pueda completarse.','Aplíquelo en vistas compuestas, informes y recuperación aumentada. No prometa coherencia que el motor o las proyecciones no sostienen.','Mida mezclas detectadas, abstenciones y atraso por revisión. Se vincula con Reconstrucción incremental y Recuperación limitada por ámbito.'],
  ['Ventana de frescura declarada','Adaptación COBRIA','Acuerdo medible','Hacer explícito cuánto atraso puede tolerar cada lectura.','Sin un límite declarado, una proyección aparentemente rápida puede entregar información inaceptablemente antigua.','Como un boletín meteorológico: su utilidad depende de cuándo fue observado y cuándo se consulta.','Cada proyección publica última revisión aplicada, tiempo de actualización y límite contratado; el lector decide esperar, degradar o fallar.','Úselo en derivados asíncronos. Defina ventanas por decisión, no una cifra universal para todo el sistema.','Mida edad, percentiles de atraso e incumplimientos. Se conecta con Reconstrucción incremental y Frontera lectura-escritura.'],
  ['Manifiesto de proyección','Adaptación COBRIA','Procedencia completa','Explicar exactamente con qué fuentes y transformación se produjo un derivado.','Una copia puede parecer correcta y aun mezclar semillas, versiones o cortes distintos.','Como la ficha de una colección científica: origen, fecha, método y responsable acompañan al conjunto.','Guarde fuentes, cortes, versiones, parámetros, semilla, huellas y resultado de verificación como manifiesto inmutable.','Úselo en índices, conjuntos analíticos y publicaciones. El manifiesto referencia secretos sin copiarlos.','Mida manifiestos incompletos, huellas inválidas y tiempo de reproducción. Se relaciona con Conjunto reproducible y Reparación verificable.'],
  ['Partición analítica sin fuga','Contrato compuesto','Evaluación válida','Separar entrenamiento, validación y prueba sin contaminar tiempo, entidad ni ámbito.','Una partición aleatoria puede colocar revisiones de la misma entidad a ambos lados y exagerar la calidad del modelo.','Como estudiar aves por rutas distintas: no se cuenta la misma bandada como descubrimiento independiente.','Particione primero por entidad y tiempo, luego por ámbito; congele reglas y audite intersecciones antes de calcular métricas.','Úselo en minería de datos y aprendizaje automático. Documente exclusiones y conserve una prueba negativa de contaminación.','Mida intersecciones, deriva temporal y rendimiento por ámbito. Se conecta con Conjunto reproducible y Característica versionada.'],
  ['Abstención con evidencia','Control de IA','Seguridad y honestidad','Responder solo cuando la evidencia autorizada sostiene la salida.','Un sistema generativo puede completar vacíos con lenguaje plausible o citar fragmentos inexistentes.','Como una guía responsable: si no observa señales suficientes, declara que no puede identificar la especie.','Defina umbrales, cobertura mínima, citas válidas y causas de abstención; la generación recibe únicamente evidencia autorizada.','Úselo en asistentes y automatizaciones. La abstención debe ser útil: explique qué falta sin revelar material prohibido.','Mida precisión, cobertura, citas válidas, fugas y abstención apropiada. Se relaciona con Recuperación limitada por ámbito.'],
  ['Presupuesto de derivados','Adaptación COBRIA','Costo gobernado','Limitar cuántas copias optimizadas puede sostener responsablemente un sistema.','Cada proyección mejora una lectura local, pero añade escritura, almacenamiento, monitoreo y carga cognitiva.','Como senderos en una reserva: cada nuevo recorrido necesita propósito, mantenimiento y cierre seguro.','Toda propuesta declara beneficio, costo total, propietario, fecha de revisión y criterio de retiro antes de ser publicada.','Úselo al diseñar o revisar proyecciones. Agrupe necesidades compatibles antes de crear otra copia.','Mida uso, costo por consulta, atraso e incidentes. Se conecta con Frontera lectura-escritura y Retiro de proyección.'],
  ['Auditoría narrativa reconstruible','Experimental','Explicación reproducible','Convertir eventos técnicos en una historia verificable de decisión y cambio.','Los registros aislados muestran acciones, pero no siempre explican quién autorizó, qué versión se usó y qué consecuencia ocurrió.','Como un cuaderno de campo: cada observación enlaza lugar, momento, responsable y evidencia.','Componga una vista temporal desde eventos inmutables; mantenga enlaces al documento, revisión, ámbito, política y resultado, sin volverla autoridad.','Úselo en incidentes, decisiones asistidas y revisión regulatoria. Proteja datos sensibles y aplique retención diferenciada.','Mida eventos sin enlace, secuencias imposibles y tiempo de explicación. Se conecta con Dato fechado, Cola de salida y Herramienta gobernada.']
];
if (patterns.length === 20) patterns.push(...nuevasFichas);

function clean(value) {
  return value
    .replace(/``([^']+)''/g, '“$1”')
    .replace(/\\Delta/g, 'Δ').replace(/\\ll/g, '≪').replace(/\\leq/g, '≤')
    .replace(/\\,/g, ' ').replace(/~|\\par/g, ' ')
    .replace(/\\text(?:bf|sf)\{([^{}]+)\}/g, '$1')
    .replace(/\$([^$]+)\$/g, '<em>$1</em>')
    .replace(/--/g, '—').replace(/\\/g, '')
    .replace(/\s+/g, ' ').trim();
}

const visualByPattern = {
  2: ['assets/repositorio-ambito-sin-felinos-v2.png', 'Antes: los ámbitos se mezclan. Después: el acceso decide el sendero antes de recuperar documentos.'],
  3: ['assets/catalogo-versionado-v1.png', 'Las ediciones separadas permiten interpretar cada valor y aislar los desconocidos.'],
  6: ['assets/ecosistema-cobria-panoramico-v4.png', 'La fuente permanece intacta mientras una versión derivada se reconstruye y verifica.'],
  15: ['assets/linaje-ia-v1.png', 'La evidencia conserva un hilo visible desde el documento hasta la recuperación autorizada.']
};

const exercises = [
  'Dibuje las rutas de escritura actuales. Marque cuál puede cambiar una regla de dominio y cierre las demás.',
  'Elija un hecho tardío y reconstruya qué se sabía antes y después de su registro.',
  'Escriba tres pruebas negativas: ámbito ausente, manipulado y válido con recurso ajeno.',
  'Tome un código ambiguo y defina versión, vigencia, sustitución y cuarentena.',
  'Seleccione una consulta lenta y escriba exactamente filtros, orden, salida y frescura.',
  'Quite todos los campos no usados por la consulta y vuelva a medir bytes y costo.',
  'Elimine una copia en un entorno aislado y regenérela sin tocar la fuente.',
  'Procese dos veces el mismo lote y compare el resultado con una reconstrucción total.',
  'Construya una candidata, interrumpa antes del cambio y compruebe que la activa sigue completa.',
  'Entregue dos veces el mismo mensaje y compruebe que solo existe un efecto.',
  'Envíe una revisión antigua y verifique rechazo, auditoría y ausencia de regresión.',
  'Interrumpa el publicador después de guardar la entidad y confirme que el evento sigue recuperable.',
  'Corrompa una muestra derivada, detecte la divergencia y repare desde canónicos.',
  'Reconstruya el mismo corte dos veces y compare manifiesto, conteos y huellas.',
  'Cambie una definición de variable y confirme que produce una versión nueva.',
  'Intente recuperar un fragmento de otro ámbito y compruebe que nunca fue candidato.',
  'Repita una acción de alto riesgo sin confirmación y exija abstención auditable.',
  'Calcule el punto de equilibrio con costos medidos y repita con el doble de escrituras.',
  'Añada primero un índice documental equivalente y mida antes de crear una copia.',
  'Identifique una proyección sin uso, simule el retiro y verifique consumidores y reversión.'
  ,'Cambie ubicación y nombre externo de diez documentos y demuestre que sus referencias internas permanecen válidas.'
  ,'Diseñe cinco entradas inválidas y compruebe rechazo completo, causa legible y ausencia de efectos parciales.'
  ,'Lea documentos de tres versiones, migre dos veces la misma muestra y compare huellas.'
  ,'Combine dos proyecciones con atraso distinto y compruebe que nunca se presenta una revisión mezclada.'
  ,'Supere deliberadamente la ventana de frescura y verifique espera, degradación y fallo según contrato.'
  ,'Reconstruya una proyección únicamente desde su manifiesto y registre cualquier dato implícito faltante.'
  ,'Particione un conjunto por entidad y tiempo; escriba una prueba que falle ante cualquier intersección.'
  ,'Retire evidencia suficiente y compruebe que la respuesta se abstiene con una explicación segura.'
  ,'Calcule el costo anual de tres derivados y retire o combine el que no justifique su mantenimiento.'
  ,'Reconstruya la narración de un incidente desde eventos y señale cada afirmación sin evidencia enlazada.'
];

const contracts = [
  'guardar(cambio) → validar → escribirCanónico → emitirRevisión',
  'registrar(hecho, válidoEn, conocidoEn, procedencia)',
  'obtener(ámbito, identidad) o fallarAntesDeLeer()',
  'resolver(clave, versión, fecha) o ponerEnCuarentena()',
  'proyectar(fuente, transformación, versión, ámbito)',
  'cubrir(filtros, orden, salida) sinCamposExtra()',
  'candidata = reconstruir(canónicos); verificar(candidata); publicar()',
  'desde(puntoDeControl).procesarUnaVezPorRevisión()',
  'construir(vNueva); verificar(); cambiarAlias(); conservar(vAnterior)',
  'si procesado(idMensaje) entonces noHacerNada()',
  'si revisiónEsperada ≠ revisiónActual entonces rechazar()',
  'enUnaOperación { guardarCanónico(); guardarEventoSalida(); }',
  'si !equivalente(derivado, esperado) entonces reconstruirYVerificar()',
  'conjunto = construir(corte, fuentes, versiones, semilla)',
  'característica = calcular(definición, tiempoEvento, versión)',
  'candidatos = buscar(dentroDe(ámbito, política), consulta)',
  'herramienta.validar(); exigirCapacidad(); confirmarSiRiesgo(); auditar()',
  'adoptar si ahorroLectura > costoEscritura + costoOperacional',
  'medir(consultaConÍndice) antesDe crearProyección()',
  'detenerConsumidores(); retirarProductor(); esperar(); eliminarDerivado()'
  ,'identidad = asignar(ámbito); referencias.usar(identidad)'
  ,'validar(entrada, contrato, ámbito) o rechazarSinEfectos()'
  ,'leer(según versión); migrar(de, hacia) deFormaIdempotente()'
  ,'leerTodoEn(revisiónObjetivo) o declararDegradación()'
  ,'si edad > ventana entonces esperar | degradar | fallar'
  ,'manifiesto = sellar(fuentes, cortes, versiones, semilla, huellas)'
  ,'partirPor(entidad, tiempo, ámbito); exigir(intersección = ∅)'
  ,'si evidenciaInsuficiente entonces abstener(causaSegura)'
  ,'autorizarDerivado soloSi beneficio > costoTotal y tieneRetiro'
  ,'narrar(eventosOrdenados); exigirEnlace(documento, revisión, política)'
];

const names = ['Propósito','Problema','Analogía','Solución y contrato','Aplicación responsable','Métricas, costos y relaciones'];
const familyByPattern = [
  'Modelado documental','Modelado documental','Seguridad por ámbito','Catálogos y vocabularios',
  'Proyecciones de lectura','Proyecciones de lectura','Reconstrucción','Reconstrucción','Eventos y consistencia','Eventos y consistencia',
  'Eventos y consistencia','Eventos y consistencia','Reconstrucción','Analítica reproducible','Analítica reproducible',
  'IA con procedencia','IA con procedencia','Gobernanza del ciclo de vida','Gobernanza del ciclo de vida','Gobernanza del ciclo de vida',
  'Modelado documental','Modelado documental','Modelado documental','Eventos y consistencia','Eventos y consistencia',
  'Reconstrucción','Analítica reproducible','IA con procedencia','Gobernanza del ciclo de vida','Modelado documental'
];
const visualByFamily = {
  'Modelado documental': ['assets/familia-modelado-validacion-v1.png','La identidad, la validación y las versiones convierten entradas dispersas en documentos interpretables.'],
  'Tiempo y evidencia': ['assets/familia-eventos-consistencia-v1.png','El orden, el atraso y la procedencia viajan con cada observación.'],
  'Seguridad por ámbito': ['assets/repositorio-ambito-sin-felinos-v2.png','El sendero autorizado se decide antes de recuperar documentos.'],
  'Catálogos y vocabularios': ['assets/catalogo-versionado-v1.png','Cada edición conserva el significado con el que fue interpretado un valor.'],
  'Proyecciones de lectura': ['assets/ecosistema-cobria-panoramico-v4.png','Los nidos sirven lecturas distintas sin desplazar la autoridad de las raíces.'],
  'Reconstrucción': ['assets/ecosistema-cobria-panoramico-v4.png','Una representación derivada vuelve a producirse y se compara con la fuente.'],
  'Publicación y migración': ['assets/ecosistema-cobria-panoramico-v4.png','La versión candidata se verifica antes de sustituir a la activa.'],
  'Eventos y consistencia': ['assets/familia-eventos-consistencia-v1.png','Eventos repetidos, tardíos y ordenados atraviesan una ruta observable.'],
  'Analítica reproducible': ['assets/familia-analitica-ia-v1.png','Particiones, transformaciones y resultados mantienen un linaje visible.'],
  'IA con procedencia': ['assets/linaje-ia-v1.png','La respuesta enlaza evidencia autorizada o se abstiene cuando no la posee.'],
  'Decisión arquitectónica': ['assets/familia-gobernanza-retiro-v1.png','Cada sendero optimizado exige propósito, medición, mantenimiento y posible cierre.'],
  'Gobernanza del ciclo de vida': ['assets/familia-gobernanza-retiro-v1.png','La arquitectura conserva rutas útiles y retira las que ya no justifican su costo.']
};
const participants = ['Fuente canónica','Contrato','Repositorio','Catálogo','Proyector','Verificador','Consumidor'];
const related = (index) => [patterns[(index + 1) % patterns.length][0], patterns[(index + 6) % patterns.length][0], patterns[(index + 13) % patterns.length][0]];
const practicalExamples = JSON.parse(fs.readFileSync(path.join(import.meta.dirname,'practical-examples.json'),'utf8'));
const codeEscape = value => value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const implementations = (p, index) => {
  if (practicalExamples[index]?.code) return practicalExamples[index].code;
  const name = clean(p[0]).replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ0-9]/g, '') || `Patron${index + 1}`;
  const contract = clean(p[3]);
  return {
    TypeScript: `type Documento = { id: string; ambito: string; revision: number };\n\nclass ${name} {\n  ejecutar(doc: Documento): Documento {\n    if (!doc.ambito) throw new Error('Ámbito requerido');\n    // ${contract}\n    return { ...doc };\n  }\n}`,
    Python: `from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Documento:\n    id: str\n    ambito: str\n    revision: int\n\ndef aplicar(doc: Documento):\n    assert doc.ambito, "Ámbito requerido"\n    # ${contract}\n    return doc`,
    Java: `record Documento(String id, String ambito, long revision) {}\n\nfinal class ${name} {\n  Documento ejecutar(Documento doc) {\n    if (doc.ambito().isBlank())\n      throw new IllegalArgumentException("Ámbito requerido");\n    // ${contract}\n    return doc;\n  }\n}`,
    Go: `type Documento struct {\n  ID string\n  Ambito string\n  Revision int64\n}\n\nfunc Aplicar(doc Documento) (Documento, error) {\n  if doc.Ambito == "" {\n    return doc, errors.New("ámbito requerido")\n  }\n  // ${contract}\n  return doc, nil\n}`
  };
};
const cards = patterns.map((p, index) => {
  const body = p.slice(3).map(clean);
  const blocks = body.map((value, i) => `<section class="block ${i === 2 ? 'analogy' : ''} ${i === 3 ? 'solution' : ''}"><h2>${names[i]}</h2><p>${value}</p></section>`).join('');
  const family = familyByPattern[index];
  const visual = visualByPattern[index] || visualByFamily[family];
  const illustration = visual ? `<figure class="story-illustration"><img src="${visual[0]}" alt="Ilustración pedagógica de ${clean(p[0])}"><figcaption>${visual[1]}</figcaption></figure>` : '';
  const links = related(index);
  const mechanism = `<article class="book-page mechanism-page"><div class="eyebrow">Mecánica · ${family}</div><h1>Cómo funciona ${clean(p[0])}</h1><p class="lead">La estructura convierte el propósito en responsabilidades separadas y comprobables.</p><div class="flow">${participants.slice(0,5).map((x,i)=>`<div><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><h2>Secuencia</h2><ol class="steps"><li>El consumidor expresa identidad, ámbito, revisión y necesidad de lectura.</li><li>El contrato valida precondiciones antes de tocar la colección.</li><li>El repositorio recupera o modifica únicamente el documento autorizado.</li><li>El mecanismo produce evidencia versionada y nunca suplanta la autoridad.</li><li>El verificador compara resultado, límites y caso negativo.</li></ol><h2>Pseudocódigo neutral</h2><pre>${contracts[index]}</pre><div class="note"><strong>Invariante principal.</strong> ${body[0]}</div><footer>COBRIA · Mecánica del patrón ${String(index+1).padStart(2,'0')}</footer></article>`;
  const decision = `<article class="book-page decision-page"><div class="eyebrow">Decidir con criterio</div><h1>Cuándo usarlo y cuándo evitarlo</h1><div class="decision-grid"><section><h2>Conviene cuando</h2><ul><li>la tensión descrita aparece en mediciones o incidentes;</li><li>existe una persona responsable del contrato;</li><li>puede probarse reconstrucción, rechazo o abstención;</li><li>el beneficio supera el costo operativo completo.</li></ul></section><section class="avoid"><h2>No conviene cuando</h2><ul><li>un índice o validación más simple resuelve la necesidad;</li><li>la copia no tiene consumidor ni límite de frescura;</li><li>se intenta ocultar una autoridad ambigua;</li><li>no existe mecanismo de reversión o retiro.</li></ul></section></div><h2>Consecuencias</h2><table><tr><th>Beneficio</th><th>Costo o riesgo</th><th>Control</th></tr><tr><td>${body[0]}</td><td>${body[1]}</td><td>Contrato, métrica y prueba negativa</td></tr><tr><td>Responsabilidad visible</td><td>Más disciplina documental</td><td>Rúbrica y revisión periódica</td></tr></table><h2>Errores frecuentes</h2><p>Aplicarlo por nombre, omitir el ámbito, aceptar revisiones implícitas o medir únicamente el caso feliz. La solución se considera incompleta si no puede explicar su fallo.</p><div class="connections"><strong>Conecta con:</strong> ${links.join(' · ')}</div><footer>COBRIA · Decisión arquitectónica</footer></article>`;
  const lab = `<article class="lab-page">
    <div class="eyebrow">Laboratorio de campo · ${String(index + 1).padStart(2,'0')}</div>
    <h1>${clean(p[0])}</h1>
    <p class="lab-lead">Ahora convierta la idea en una prueba pequeña, observable y reversible.</p>
    <section class="field-card"><h2>Situación para diagnosticar</h2><p>${body[1]}</p></section>
    <div class="lab-grid"><section><h2>Ejercicio</h2><p>${exercises[index]}</p></section><section><h2>Resultado que debe conservar</h2><p>${body[0]}</p></section></div>
    <section><h2>Contrato mínimo</h2><pre>${contracts[index]}</pre></section>
    <div class="lab-grid"><section><h2>Preguntas de revisión</h2><ul><li>¿Quién posee la autoridad?</li><li>¿Dónde aparece el ámbito y la versión?</li><li>¿Cómo se prueba el fallo?</li><li>¿Cómo se revierte o reconstruye?</li></ul></section><section><h2>Evidencia para guardar</h2><ul><li>manifiesto y versión;</li><li>entrada y resultado esperado;</li><li>métrica y límite;</li><li>captura del caso negativo.</li></ul></section></div>
    <section class="field-card relation"><h2>Conexiones</h2><p>${body[5]}</p></section>
    <footer>COBRIA · Laboratorio NoSQL · Billy Jak Cordero Porras</footer>
  </article>`;
  const reference = `<article class="book-page reference-page"><div class="eyebrow">Tarjeta de referencia · ${String(index+1).padStart(2,'0')}</div><h1>${clean(p[0])}</h1><div class="reference-grid"><section><h2>Contrato de aceptación</h2><ol><li>Preparar un documento válido y otro inválido.</li><li>Ejecutar ${clean(p[0]).toLowerCase()} bajo un ámbito conocido.</li><li>Comprobar resultado, revisión y procedencia.</li><li>Repetir, interrumpir o reconstruir según corresponda.</li><li>Guardar manifiesto, métricas y causa de cualquier exclusión.</li></ol></section><section><h2>Lista de comprobación</h2><ul class="checklist"><li>Autoridad identificada</li><li>Ámbito obligatorio</li><li>Contrato versionado</li><li>Caso negativo probado</li><li>Observabilidad suficiente</li><li>Reversión o reconstrucción</li></ul></section></div><h2>Señales que debe observar</h2><p>${body[5]}</p><h2>Preguntas para revisión de diseño</h2><div class="question-grid"><p>¿Qué afirmación concreta vuelve verdadera este patrón?</p><p>¿Qué dato demuestra que continúa funcionando?</p><p>¿Qué ocurre si se repite, atrasa o interrumpe?</p><p>¿Cómo se retira sin perder la fuente?</p></div><div class="note"><strong>Regla de salida.</strong> Si no puede responder las cuatro preguntas con evidencia, el patrón aún no está implementado.</div><footer>COBRIA · Referencia rápida</footer></article>`;
  const code = implementations(p, index);
  const practical = practicalExamples[index];
  const codePage = `<article class="book-page code-page"><div class="eyebrow">Implementación comparada · ${String(index+1).padStart(2,'0')}</div><h1>${clean(p[0])}</h1><div class="book-story"><strong>${practical.escena}</strong><p>${practical.problema}</p><small>Resultado: ${practical.resultado}</small></div><p class="code-lead">El mismo caso se expresa en cuatro lenguajes. Identifique participantes y contrato antes de adaptar el ejemplo a su almacén documental.</p><div class="code-grid">${Object.entries(code).map(([language,value])=>`<section><h2>${language}</h2><pre>${codeEscape(value)}</pre></section>`).join('')}</div><div class="note"><strong>Prueba mínima.</strong> Ejecute el caso válido, elimine el dato que delimita la operación y compruebe que el fallo conserva evidencia.</div><footer>COBRIA · Código multilenguaje · Billy Jak Cordero Porras</footer></article>`;
  return `<article class="pattern ${visual ? 'illustrated' : ''}">
    <header class="pattern-head"><div class="pattern-number">${String(index + 1).padStart(2,'0')}</div><h1>${clean(p[0])}</h1></header>
    <div class="badges"><span class="badge">${clean(p[1])}</span><span class="badge">Evidencia: ${clean(p[2])}</span></div>
    <div class="pattern-grid">${illustration}${blocks}</div>
    <footer>COBRIA · Arquitecturas NoSQL reconstruibles · Billy Jak Cordero Porras</footer>
  </article>${mechanism}${decision}${lab}${reference}${codePage}`;
}).join('\n');

const frontMatter = `<section class="book-page title-page"><div class="eyebrow">Edición completa 2.0</div><h1>COBRIA</h1><p class="lead">Arquitectura de software: catálogo pedagógico de patrones NoSQL reconstruibles</p><div class="title-rule"></div><p>Billy Jak Cordero Porras<br>Coto Brus, Costa Rica · 2026</p><div class="note">Libro, guía y laboratorio para aprender a diseñar datos documentales con autoridad, trazabilidad, derivados reconstruibles y ejemplos en TypeScript, Python, Java y Go.</div></section>
<section class="book-page bibliographic-page"><div class="eyebrow">Información de la obra digital</div><h1>Datos de esta edición</h1><dl class="bibliographic-grid"><dt>Título</dt><dd>COBRIA: Arquitectura de software</dd><dt>Subtítulo</dt><dd>Catálogo pedagógico de patrones NoSQL reconstruibles</dd><dt>Autor</dt><dd>Billy Jak Cordero Porras</dd><dt>Versión</dt><dd>Edición digital 2.0 revisada</dd><dt>Lugar y fecha</dt><dd>Coto Brus, Costa Rica, 2026</dd><dt>Idioma</dt><dd>Español</dd><dt>Formato</dt><dd>Documento pedagógico digital en PDF</dd><dt>Distribución</dt><dd>Publicación independiente y gratuita del autor</dd></dl><div class="rights-box"><strong>Uso y alcance.</strong> Material educativo de acceso libre para estudio, docencia, investigación y adaptación con atribución. No constituye una edición comercial ni un estándar certificado. COBRIA integra y formaliza principios existentes con contratos y mecanismos propios; no afirma que cada elemento sea una invención aislada. Los ejemplos requieren validación antes de emplearse en producción.</div></section>
<section class="book-page bibliographic-page"><div class="eyebrow">Sinopsis</div><h1>Una arquitectura que conserva el camino de regreso</h1><div class="synopsis-box"><p>COBRIA es una propuesta pedagógica para diseñar sistemas NoSQL documentales cuya información pueda explicarse, comprobarse y reconstruirse. Organiza treinta patrones alrededor de fuentes canónicas, límites de acceso, catálogos versionados, proyecciones de lectura, eventos idempotentes, analítica reproducible e inteligencia artificial con procedencia.</p><p>El libro combina analogías inspiradas en la naturaleza de Costa Rica, contratos verificables, decisiones arquitectónicas, laboratorios y ejemplos en TypeScript, Python, Java y Go. Está dirigido a estudiantes, docentes, personas desarrolladoras, arquitectos de software y equipos que necesitan optimizar lecturas sin perder autoridad, trazabilidad ni capacidad de auditoría.</p></div><h2>Palabras clave</h2><p>Arquitectura de software; NoSQL; bases de datos documentales; patrones de diseño; trazabilidad; reconstrucción; minería de datos; inteligencia artificial; gobernanza de datos.</p><h2>Clasificación temática sugerida</h2><p>Computación y tecnología · Ingeniería de software · Bases de datos · Arquitectura de sistemas.</p></section>
<section class="book-page bibliographic-page"><div class="eyebrow">Sobre el autor</div><h1>Billy Jak Cordero Porras</h1><div class="author-profile"><div class="author-monogram">BJ</div><div><p>Billy Jak Cordero Porras es un joven cotobruseño aficionado a la informática y al desarrollo de software. Desde temprana edad ha construido sistemas para aprender y atender problemas cotidianos. Su curiosidad lo llevó a estudiar de forma autodidacta arquitectura de software, bases de datos, gestión de información e inteligencia artificial.</p><p>El trabajo con proyectos diversos lo enfrentó repetidamente al problema de conservar información comprensible, segura, trazable y útil. A partir de experimentación, comparación de patrones y revisión de errores formalizó COBRIA como investigación, artículo, libro y recurso pedagógico interactivo de acceso abierto.</p></div></div><div class="note"><strong>Principio del autor.</strong> La investigación universitaria y la creación de soluciones deben producir conocimiento comprensible, verificable y de interés público.</div></section>
<section class="book-page"><div class="eyebrow">Nota del autor</div><h1>Un lenguaje para conversar sobre datos</h1><p class="lead">COBRIA nació de observar una estructura repetida en sistemas reales: objetos que conservan reglas, repositorios que delimitan acceso, servicios que coordinan decisiones, catálogos que estabilizan significado y derivados que aceleran consultas o alimentan analítica.</p><p>Este libro no presenta cada mecanismo como una invención aislada. Reúne ideas conocidas, adaptaciones y contratos compuestos dentro de una propuesta evaluable. El lector puede adoptar una parte, medirla y rechazarla si no produce beneficio.</p><h2>Antecedentes conceptuales</h2><p>La propuesta dialoga con la tradición de patrones de diseño (Gamma et al., 1994), patrones de arquitectura empresarial (Fowler, 2002), diseño dirigido por el dominio (Evans, 2003), persistencia políglota NoSQL (Sadalage &amp; Fowler, 2012) y sistemas intensivos en datos (Kleppmann, 2017). La organización de citas y referencias sigue los criterios generales de APA 7 (American Psychological Association, 2020).</p><h2>Promesa pedagógica</h2><p>Cada capítulo responde cinco preguntas: qué tensión existe, cómo se reconoce, qué responsabilidades introduce la solución, qué puede salir mal y qué evidencia demuestra su funcionamiento.</p><div class="note"><strong>Alcance.</strong> Todo el contenido se formula para almacenes NoSQL documentales, sin depender de un producto particular.</div></section>
<section class="book-page"><div class="eyebrow">Fundamentos</div><h1>Objeto, dato, servicio y catálogo</h1><div class="concept-grid"><article><h2>Objeto</h2><p>Representa identidad y reglas que deben conservarse juntas.</p></article><article><h2>Dato fechado</h2><p>Registra valor, tiempo válido, tiempo conocido y procedencia.</p></article><article><h2>Repositorio</h2><p>Expresa el límite de acceso y evita consultas sin ámbito.</p></article><article><h2>Servicio</h2><p>Coordina una decisión que atraviesa varios objetos o mecanismos.</p></article><article><h2>Catálogo</h2><p>Estabiliza el significado de códigos, unidades y versiones.</p></article><article><h2>Proyección</h2><p>Optimiza una lectura y puede reconstruirse desde la autoridad.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Fundamentos</div><h1>Patrón, contrato, mecanismo y decisión</h1><table><tr><th>Concepto</th><th>Pregunta</th><th>Evidencia</th></tr><tr><td>Patrón</td><td>¿Qué tensión recurrente resuelve?</td><td>Contexto, solución y consecuencias</td></tr><tr><td>Contrato</td><td>¿Qué debe cumplirse siempre?</td><td>Precondición, resultado y fallo</td></tr><tr><td>Mecanismo</td><td>¿Cómo se ejecuta?</td><td>Participantes y secuencia</td></tr><tr><td>Decisión</td><td>¿Por qué conviene aquí?</td><td>Alternativas, costo y métrica</td></tr></table><p class="lead">COBRIA exige las cuatro capas. Un nombre sin contrato inspira; no gobierna. Un mecanismo sin decisión funciona; quizá no conviene.</p></section>
<section class="book-page"><div class="eyebrow">Especificación congelada</div><h1>COBRIA Core 1.0</h1><p class="lead">El núcleo normativo convierte el catálogo en una arquitectura comprobable.</p><table><tr><th>Nivel</th><th>Obligaciones</th></tr><tr><td>C1 · Fundamental</td><td>Autoridad, ámbito, identidad, revisión y frontera de escritura.</td></tr><tr><td>C2 · Reconstruible</td><td>C1 más transformación versionada, equivalencia, idempotencia, reconstrucción y publicación segura.</td></tr><tr><td>C3 · Gobernado</td><td>C2 más procedencia, frescura, observabilidad, responsable y retiro.</td></tr></table><div class="note"><strong>Regla de conformidad.</strong> Una implementación solo declara un nivel cuando supera todas sus pruebas obligatorias. El alcance confirmatorio se limita a sistemas NoSQL documentales.</div></section>
<section class="book-page"><div class="eyebrow">Precisión conceptual · Core 1.1</div><h1>Qué es COBRIA y qué no es</h1><p class="lead">Una propuesta arquitectónica verificable, no una estructura de datos ni un producto de almacenamiento.</p><div class="concept-grid"><article><h2>Núcleo</h2><p>Invariantes y requisitos obligatorios.</p></article><article><h2>Patrones</h2><p>Soluciones recurrentes que ayudan a cumplirlos.</p></article><article><h2>Mecanismos</h2><p>Índices, proyecciones, manifiestos y revisiones.</p></article><article><h2>Método</h2><p>Inventariar, decidir, verificar, observar y retirar.</p></article><article><h2>Adaptadores</h2><p>Implementaciones intercambiables para motores NoSQL.</p></article><article><h2>Evidencia</h2><p>Pruebas, métricas, límites y resultados reproducibles.</p></article></div><div class="note"><strong>Afirmación responsable.</strong> La contribución es la composición formalizada y comprobable de mecanismos conocidos; no la invención aislada de cada pieza.</div></section>
<section class="book-page"><div class="eyebrow">Caso completo · Core 1.2</div><h1>Cuando desaparece el índice del bosque</h1><p class="lead">Un solo recorrido conecta documento, contrato, fallo, reconstrucción, analítica e IA.</p><ol class="steps"><li>Una observación canónica declara identidad, ámbito, revisión y versión.</li><li>Un contrato produce una proyección de búsqueda sin autoridad propia.</li><li>La proyección activa se elimina de forma controlada.</li><li>Una candidata se reconstruye desde documentos y catálogo congelados.</li><li>La equivalencia se comprueba antes de cambiar el alias.</li><li>El corte analítico conserva partición temporal y manifiesto.</li><li>La recuperación para IA filtra ámbito antes de similitud y se abstiene sin evidencia.</li></ol><div class="note"><strong>Resultado.</strong> La búsqueda vuelve sin inventar datos; una revisión antigua no reemplaza la nueva y otro ámbito obtiene cero documentos.</div></section>
<section class="book-page"><div class="eyebrow">Aprender por contraste</div><h1>Ocho diseños que parecen funcionar</h1><div class="concept-grid"><article><h2>Proyección editable</h2><p>Crea dos autoridades.</p></article><article><h2>Ámbito al final</h2><p>Filtra después de revelar candidatos.</p></article><article><h2>Revisión obsoleta</h2><p>Hace retroceder el estado visible.</p></article><article><h2>Vector sin manifiesto</h2><p>Oculta corpus, modelo y corte.</p></article><article><h2>Fuga temporal</h2><p>El futuro contamina la evaluación.</p></article><article><h2>Reparar desde lo dañado</h2><p>Propaga la corrupción.</p></article><article><h2>Publicación destructiva</h2><p>Deja lectores sin versión.</p></article><article><h2>IA que siempre responde</h2><p>Inventa cuando falta evidencia.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Banco de fallos · Core 1.2</div><h1>La arquitectura se aprende cuando algo se rompe</h1><p class="lead">Se ejecutaron 300 pruebas locales: diez fallos, treinta repeticiones por escenario.</p><table><tr><th>Familia</th><th>Escenarios</th><th>Resultado final</th></tr><tr><td>Pérdida</td><td>Eliminación y corrupción parcial</td><td>30/30 cada uno</td></tr><tr><td>Orden</td><td>Duplicado y revisión obsoleta</td><td>30/30 cada uno</td></tr><tr><td>Interrupción</td><td>25 %, 50 % y 75 %</td><td>30/30 cada uno</td></tr><tr><td>Evolución</td><td>Esquema y catálogo</td><td>30/30 tras corregir migración</td></tr><tr><td>Seguridad</td><td>Fuga de ámbito</td><td>Cero cruces</td></tr></table><div class="note"><strong>Hallazgo.</strong> La primera corrida descubrió que el cambio de esquema no estaba modelado. Corregirlo antes de publicar fue parte del resultado, no un dato que ocultar.</div></section>
<section class="book-page"><div class="eyebrow">Rutas de lectura</div><h1>Seis maneras de comenzar</h1><div class="route-grid"><article><h2>Principiante</h2><p>Caso → Canónico → Ámbito → Proyección → Reconstrucción.</p></article><article><h2>Arquitectura</h2><p>Modelo → Core → Fronteras → Presupuesto → Retiro.</p></article><article><h2>NoSQL</h2><p>Identidad → Revisión → Versiones → Publicación.</p></article><article><h2>Minería</h2><p>Dato fechado → Conjunto → Partición → Manifiesto.</p></article><article><h2>IA</h2><p>Recuperación → Evidencia → Abstención → Auditoría.</p></article><article><h2>Conformidad</h2><p>Requisitos → Amenazas → P1–A1 → D1–D8.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Evidencia reproducible</div><h1>Primera réplica NoSQL de Core 1.0</h1><p class="lead">Se ejecutaron 180 corridas sobre PouchDB y LokiJS: dos motores documentales, tres escalas y treinta repeticiones por celda.</p><div class="concept-grid"><article><h2>P1</h2><p>Lecturas equivalentes; la proyección redujo la mediana en las seis celdas.</p></article><article><h2>P2</h2><p>Amplificación observada: dos escrituras por cambio proyectado.</p></article><article><h2>R1</h2><p>Reconstrucción total equivalente e idempotente.</p></article><article><h2>S1</h2><p>Cero documentos cruzados y rechazo sin ámbito.</p></article><article><h2>A1</h2><p>Manifiesto, procedencia y partición temporal verificables.</p></article><article><h2>Límite</h2><p>Evidencia embebida; no representa redes, regiones ni facturación administrada.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Estadística ampliada</div><h1>Leer más allá de la mediana</h1><p class="lead">Core 1.1 informa p50, p95, p99, desviación absoluta mediana e intervalos bootstrap del 95 %.</p><table><tr><th>Motor · N</th><th>R1 p50</th><th>R1 p95</th><th>IC95 de la mediana</th></tr><tr><td>LokiJS · 5 000</td><td>45,932 ms</td><td>50,859 ms</td><td>45,260–46,864 ms</td></tr><tr><td>PouchDB · 5 000</td><td>499,896 ms</td><td>521,530 ms</td><td>495,701–502,708 ms</td></tr></table><p>No se eliminaron valores atípicos. Se utilizaron 4 000 remuestras y semilla registrada. La réplica distribuida posterior conserva por separado sus versiones, parámetros y resultados, de modo que las cifras embebidas no se confundan con las obtenidas mediante servicios.</p><div class="note"><strong>Regla editorial.</strong> Código disponible no significa evidencia ejecutada; cada afirmación debe señalar motor, versión, protocolo y fecha.</div></section>
<section class="book-page"><div class="eyebrow">Réplica distribuida · Core 1.2</div><h1>La misma prueba en tres servicios NoSQL</h1><p class="lead">El archivo conserva 270 corridas históricas: MongoDB 8.0, CouchDB 3.4 y OpenSearch 2.19.3; tres escalas y treinta repeticiones por motor y escala.</p><table><tr><th>Motor · N</th><th>Canónico p50</th><th>Proyección p50</th><th>R1 p50</th></tr><tr><td>MongoDB 8.0 · 5 000</td><td>157,856 ms</td><td>129,272 ms</td><td>3 179,603 ms</td></tr><tr><td>CouchDB 3.4 · 5 000</td><td>4 298,485 ms</td><td>1 477,093 ms</td><td>12 844,488 ms</td></tr><tr><td>OpenSearch 2.19.3 · 5 000</td><td>450,837 ms</td><td>250,173 ms</td><td>2 998,821 ms</td></tr></table><div class="concept-grid"><article><h2>Estado</h2><p>El oráculo original aprobó P1, P2, R1, S1 y A1; deben repetirse con el arnés corregido.</p></article><article><h2>Aislamiento observado</h2><p>No se registraron cruces de ámbito en la muestra histórica.</p></article><article><h2>Comparación</h2><p>Las latencias describen este entorno; no son una clasificación universal de motores.</p></article><article><h2>Clasificación correcta</h2><p>Son evidencia histórica de portabilidad, no certificación vigente.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Transparencia experimental</div><h1>Un fallo de plataforma también es evidencia</h1><p class="lead">OpenSearch 3.2.0 con Java 24 terminó por un fallo nativo al ejecutarse bajo emulación x86_64. La réplica confirmatoria se realizó con OpenSearch 2.19.3 y Java 21.</p><div class="decision-grid"><section><h2>Lo que sí puede afirmarse</h2><ul><li>el adaptador superó las pruebas con OpenSearch 2.19.3;</li><li>el protocolo, los tamaños y las repeticiones quedaron registrados;</li><li>la incidencia y la sustitución de versión permanecen visibles.</li></ul></section><section class="avoid"><h2>Lo que no puede afirmarse</h2><ul><li>que OpenSearch 3.2.0 fue validado;</li><li>que una sola máquina representa producción;</li><li>que la comparación predice costos de nube o red.</li></ul></section></div><div class="note"><strong>Lección.</strong> La reproducibilidad no consiste en ocultar obstáculos, sino en separar con precisión lo ejecutado, lo fallido y lo pendiente.</div></section>
<section class="book-page"><div class="eyebrow">Seguridad por diseño</div><h1>Doce amenazas que una proyección debe enfrentar</h1><div class="decision-grid"><section><h2>Datos y ámbitos</h2><ul><li>confusión entre organizaciones;</li><li>edición directa del derivado;</li><li>repetición y revisión obsoleta;</li><li>manipulación de proyecciones;</li><li>eliminación incompleta;</li><li>dependencia del proveedor.</li></ul></section><section><h2>Publicación, analítica e IA</h2><ul><li>fallo durante publicación;</li><li>envenenamiento analítico;</li><li>recuperación no autorizada;</li><li>evidencia insuficiente;</li><li>herramientas excesivas;</li><li>pérdida de procedencia.</li></ul></section></div><div class="note"><strong>Límite.</strong> COBRIA complementa, pero no reemplaza, autenticación, cifrado, respaldo o consenso del motor.</div></section>
<section class="book-page"><div class="eyebrow">Mapa general</div><h1>Nueve familias, una arquitectura</h1><div class="family-map">${[...new Set(familyByPattern)].map((f,i)=>`<article><b>${String(i+1).padStart(2,'0')}</b><h2>${f}</h2><p>${familyByPattern.filter(x=>x===f).length} patrones</p></article>`).join('')}</div></section>
<section class="book-page"><div class="eyebrow">Ruta de aprendizaje</div><h1>Tres maneras de recorrer el atlas</h1><div class="route-grid"><article><h2>Ruta esencial</h2><p>Objeto canónico → Repositorio con ámbito → Catálogo versionado → Proyección de lectura → Reconstrucción total.</p></article><article><h2>Ruta analítica</h2><p>Dato fechado → Conjunto reproducible → Característica versionada → Partición sin fuga → Manifiesto.</p></article><article><h2>Ruta de IA</h2><p>Recuperación limitada → Abstención con evidencia → Herramienta gobernada → Auditoría narrativa.</p></article></div></section>
<section class="book-page"><div class="eyebrow">Regla de lectura</div><h1>De la analogía a la prueba</h1><ol class="big-steps"><li><b>Observar.</b> Reconozca el problema en una consulta, incidente o decisión.</li><li><b>Delimitar.</b> Identifique autoridad, ámbito, revisión y consumidor.</li><li><b>Contratar.</b> Escriba qué debe ocurrir y cómo falla.</li><li><b>Instrumentar.</b> Conserve métricas y procedencia.</li><li><b>Desafiar.</b> Pruebe repetición, atraso, interrupción y acceso prohibido.</li><li><b>Retirar.</b> Simplifique cuando el beneficio desaparezca.</li></ol></section>
<section class="book-page"><div class="eyebrow">Vocabulario visual</div><h1>La metáfora del bosque documental</h1><p class="lead">Las raíces representan documentos canónicos; el tronco, contratos; las ramas, servicios; los nidos, proyecciones; los senderos, ámbitos; y los colibríes, eventos que transportan cambios.</p><div class="note">La metáfora ayuda a recordar, pero la evidencia decide. Ninguna ilustración sustituye el contrato, la métrica o la prueba.</div><h2>Fauna y flora</h2><p>Las escenas emplean colibríes, ranas, tucanes, mariposas, perezosos y dantas junto con paisajes de Coto Brus.</p></section>`;

const cases = [
  ['Reservas y servicios','Una organización administra alojamientos, disponibilidad, servicios y cobros documentales.','Objeto canónico, Catálogo versionado, Proyección de lectura, Cola de salida transaccional, Ventana de frescura declarada'],
  ['Seguimiento deportivo','Un programa registra sesiones, planteles, métricas fechadas y análisis longitudinal.','Dato fechado, Repositorio con ámbito, Conjunto reproducible, Característica versionada, Partición sin fuga'],
  ['Gestión territorial comunitaria','Equipos de campo documentan solicitudes, visitas, evidencia y decisiones con acceso delimitado.','Identidad estable, Validación en frontera, Auditoría narrativa, Recuperación limitada y Abstención con evidencia']
].map((c,i)=>`<section class="book-page case-cover"><div class="eyebrow">Caso guiado ${i+1}</div><h1>${c[0]}</h1><p class="lead">${c[1]}</p><div class="note"><strong>Patrones principales.</strong> ${c[2]}.</div></section><section class="book-page"><div class="eyebrow">Caso ${i+1} · Diseño</div><h1>Del lenguaje del dominio al documento</h1><h2>Decisiones</h2><ol class="steps"><li>Definir identidad y ámbito antes de elegir colecciones.</li><li>Separar hechos históricos de estados reemplazables.</li><li>Versionar vocabularios y contratos desde la primera migración.</li><li>Diseñar cada proyección desde una consulta concreta.</li></ol><h2>Documento mínimo</h2><pre>{ identidad, ámbito, revisión, contrato, datos, procedencia }</pre><div class="note">La forma final cambia con el dominio; los campos de gobierno permanecen verificables.</div></section><section class="book-page"><div class="eyebrow">Caso ${i+1} · Fallos</div><h1>Ensayo de degradación</h1><table><tr><th>Fallo</th><th>Respuesta esperada</th></tr><tr><td>Evento duplicado</td><td>Un solo efecto por revisión</td></tr><tr><td>Proyección atrasada</td><td>Frescura visible y degradación declarada</td></tr><tr><td>Ámbito manipulado</td><td>Rechazo antes de recuperar documentos</td></tr><tr><td>Cambio incompatible</td><td>Nueva versión y convivencia controlada</td></tr></table><h2>Evidencia</h2><p>Guarde manifiesto, entradas, revisión inicial y final, métricas, caso negativo y procedimiento de reversión.</p></section><section class="book-page"><div class="eyebrow">Caso ${i+1} · Revisión</div><h1>Preguntas para el equipo</h1><div class="question-grid"><p>¿Dónde vive la única autoridad de cambio?</p><p>¿Qué copia puede borrarse hoy?</p><p>¿Qué lectura tolera atraso y cuánto?</p><p>¿Qué dato no debe cruzar un ámbito?</p><p>¿Cómo se reproduce una cifra analítica?</p><p>¿Qué mecanismo podría retirarse?</p></div><div class="note"><strong>Cierre.</strong> El caso termina cuando otra persona puede reconstruir la decisión sin preguntarle al autor.</div></section>`).join('');

const workshop = `<section class="book-page"><div class="eyebrow">Taller práctico</div><h1>Construya una arquitectura COBRIA</h1><p class="lead">Ocho estaciones convierten un problema real en un diseño verificable. Trabaje con una muestra pequeña y conserve cada decisión.</p></section>${['Inventario de decisiones y consumidores','Diseño de documentos e identidad','Contratos, ámbito y validación','Catálogos y evolución semántica','Proyecciones e índices','Reconstrucción, eventos y reparación','Minería de datos e inteligencia artificial','Evaluación, costos y retiro'].map((x,i)=>`<section class="book-page"><div class="eyebrow">Estación ${i+1} de 8</div><h1>${x}</h1><h2>Producto de la estación</h2><p>${['Mapa de escrituras, lecturas, responsables y consecuencias.','Tres documentos con identidad, revisión, tiempos y procedencia.','Contrato de éxito, rechazo y acceso prohibido.','Una entrada versionada con vigencia, sustitución y cuarentena.','Ficha de consulta con filtros, orden, salida, frescura y presupuesto.','Manifiesto y prueba de equivalencia incremental frente a total.','Partición sin fuga, definición versionada y política de abstención.','Tabla comparativa, umbrales, rúbrica y procedimiento de retiro.'][i]}</p><h2>Trabajo</h2><ol class="steps"><li>Describa el estado inicial con un ejemplo concreto.</li><li>Escriba el contrato antes de implementar.</li><li>Diseñe un caso feliz y dos negativos.</li><li>Defina la evidencia que conservará.</li><li>Revise con una persona que no participó en el diseño.</li></ol><div class="note"><strong>Criterio de avance.</strong> No continúe si la autoridad, el ámbito o la evidencia siguen implícitos.</div></section>`).join('')}`;

const glossaryTerms = [['Autoridad','Lugar autorizado para aceptar un cambio legítimo.'],['Ámbito','Límite organizacional o de seguridad que acompaña toda operación.'],['Canónico','Documento desde el cual los derivados pueden volver a producirse.'],['Catálogo','Vocabulario versionado que estabiliza significado.'],['Contrato','Condición observable de entrada, resultado y fallo.'],['Corte','Punto temporal o de revisión usado para reproducir un conjunto.'],['Derivado','Representación orientada a una lectura, analítica o IA.'],['Frescura','Edad observable de una proyección frente a su fuente.'],['Idempotencia','Propiedad por la cual repetir no añade efectos distintos.'],['Linaje','Enlaces entre fuente, transformación, versión y resultado.'],['Manifiesto','Registro sellado de materiales y parámetros de construcción.'],['Procedencia','Origen y transformación documentados de un dato.'],['Proyección','Derivado diseñado para una necesidad concreta.'],['Reconstrucción','Producción repetible de un derivado desde fuentes autorizadas.'],['Revisión','Número o marca monotónica que evita regresiones silenciosas.'],['Tiempo conocido','Momento en que el sistema aprendió un hecho.'],['Tiempo válido','Momento del mundo al que el hecho se refiere.'],['Ventana','Atraso máximo aceptado por una lectura.']];
const glossary = Array.from({length:6},(_,page)=>`<section class="book-page"><div class="eyebrow">Glosario ilustrado · ${page+1}/6</div><h1>Lenguaje COBRIA</h1>${glossaryTerms.slice(page*3,page*3+3).map(t=>`<article class="term"><h2>${t[0]}</h2><p>${t[1]}</p><small>Pregunta: ¿dónde puede observarse y cómo se prueba?</small></article>`).join('')}</section>`).join('');

const bibliography = `<section class="book-page bibliographic-page"><div class="eyebrow">Fuentes y antecedentes</div><h1>Bibliografía seleccionada</h1><p>Estas obras permiten situar COBRIA frente a patrones de diseño, diseño dirigido por el dominio, sistemas de datos y bases NoSQL. Las referencias se presentan conforme a la estructura autor-fecha-título-fuente de APA 7.</p><p class="apa-reference">American Psychological Association. (2020). <em>Publication manual of the American Psychological Association</em> (7th ed.).</p><p class="apa-reference">Evans, E. (2003). <em>Domain-driven design: Tackling complexity in the heart of software</em>. Addison-Wesley.</p><p class="apa-reference">Fowler, M. (2002). <em>Patterns of enterprise application architecture</em>. Addison-Wesley.</p><p class="apa-reference">Gamma, E., Helm, R., Johnson, R., &amp; Vlissides, J. (1994). <em>Design patterns: Elements of reusable object-oriented software</em>. Addison-Wesley.</p><p class="apa-reference">Kleppmann, M. (2017). <em>Designing data-intensive applications: The big ideas behind reliable, scalable, and maintainable systems</em>. O'Reilly Media.</p><p class="apa-reference">Sadalage, P. J., &amp; Fowler, M. (2012). <em>NoSQL distilled: A brief guide to the emerging world of polyglot persistence</em>. Addison-Wesley.</p><div class="note"><strong>Criterio editorial.</strong> Una fuente incluida aquí debe aparecer cuando sustenta una afirmación del texto; a su vez, toda cita del texto debe tener su entrada completa en la bibliografía.</div></section>`;

const theme = fs.readFileSync(path.join(import.meta.dirname, 'theme.css'), 'utf8');
const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>COBRIA · Catálogo pedagógico</title><style>${theme}</style></head><body>
<section class="cover"><img src="assets/ecosistema-cobria-sin-felinos-v3.png" alt="Ecosistema COBRIA ilustrado"><div class="cover-title"><div class="kicker">Arquitecturas NoSQL reconstruibles</div><h1>COBRIA</h1><h2>Patrones, contratos, mecanismos y laboratorios</h2></div><div class="cover-author">Billy Jak Cordero Porras<br>Coto Brus, Costa Rica · 2026</div><div class="edition-chip">Edición digital 2.0</div></section>
${frontMatter}
${cards}
${cases}${workshop}${glossary}
<section class="book-page"><div class="eyebrow">Índice de decisiones</div><h1>¿Por dónde comienzo?</h1><table><tr><th>Necesidad</th><th>Primer patrón</th></tr><tr><td>No sé cuál copia contiene la verdad</td><td>Objeto canónico</td></tr><tr><td>Se cruzan organizaciones o permisos</td><td>Repositorio con ámbito</td></tr><tr><td>Los códigos cambian de significado</td><td>Catálogo versionado</td></tr><tr><td>Una consulta exige otra forma</td><td>Índice antes que proyección</td></tr><tr><td>No puedo rehacer una copia</td><td>Reconstrucción total</td></tr><tr><td>Las cifras no se reproducen</td><td>Conjunto de datos reproducible</td></tr><tr><td>La IA responde sin sustento</td><td>Abstención con evidencia</td></tr></table></section>
<section class="book-page"><div class="eyebrow">Rúbrica final</div><h1>Evaluación de una arquitectura COBRIA</h1><p>Califique de cero a dos: ausente, parcial o comprobado.</p><div class="rubric">${['Autoridad única','Ámbito obligatorio','Identidad estable','Revisión monotónica','Contrato versionado','Procedencia','Reconstrucción','Frescura observable','Caso negativo','Retiro seguro'].map(x=>`<div><span>${x}</span><b>0 · 1 · 2</b></div>`).join('')}</div><div class="note">Un cero en autoridad o aislamiento no se compensa con promedios altos.</div></section>
${bibliography}
<section class="closing"><div class="eyebrow">Cierre</div><h1>Diseñar también es dejar un camino de regreso</h1><p class="lead">COBRIA propone una disciplina sencilla de expresar y exigente de demostrar: una fuente autorizada, límites explícitos y derivados útiles que puedan explicarse, comprobarse, reconstruirse y retirarse.</p><p>Este libro contiene treinta patrones, treinta laboratorios, tres casos guiados, ocho estaciones de taller y un glosario operativo. El atlas interactivo amplía la exploración mediante búsqueda, comparación y simulación.</p><div class="note"><strong>Última pregunta.</strong> Si mañana desapareciera una proyección, ¿su equipo sabría reconstruirla sin inventar información?</div></section>
</body></html>`;

fs.writeFileSync(path.join(import.meta.dirname, 'index.html'), html);
const sitePublic = path.resolve(root, '..', 'COBRIA-atlas', 'public');
if (fs.existsSync(path.dirname(sitePublic))) {
  fs.mkdirSync(sitePublic, { recursive: true });
  const catalogo = patterns.map((p,index) => ({
    id: index + 1,
    slug: clean(p[0]).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),
    nombre: clean(p[0]), familia: familyByPattern[index], tipo: clean(p[1]), evidencia: clean(p[2]),
    proposito: clean(p[3]), problema: clean(p[4]), analogia: clean(p[5]), solucion: clean(p[6]),
    aplicacion: clean(p[7]), metricas: clean(p[8]), contrato: contracts[index], ejercicio: exercises[index],
    relaciones: related(index)
  }));
  fs.writeFileSync(path.join(sitePublic, 'catalogo.json'), JSON.stringify(catalogo, null, 2));
}
console.log(`Libro construido con ${patterns.length} fichas.`);
